import {
  createGuidedAssessment,
  createGuidedAssetManifest,
  createGuidedLesson,
  createGuidedModuleRecord,
  defineGuidedImplementedSimulation,
  type GuidedStageAuthoring,
} from './builders.js';

const moduleId = 'sim-c08-ch01-a05-harvesting-threshing-and-storage-of-crops';
const slug = 'c8-ch01-a05-harvesting-threshing-and-storage-of-crops';
const viewerKey = 'guided-harvesting-threshing-storage';

const stages = [
  {
    id: 'crop-ready',
    title: 'Is the Crop Ready?',
    cue: 'Compare the green crop with the golden-yellow crop, then inspect the grain in each plot.',
    detail: 'A mature cereal crop is commonly golden-yellow and dry, with full, firm grain. A green crop with soft grain is still immature.',
    actionId: 'inspect-cereal-crop-maturity',
    actionLabel: 'Inspect both crop plots',
    evidenceId: 'mature-crop-evidence',
    evidenceMode: 'scene',
    narrationText: 'Welcome to the crop field. Several months have passed since sowing. Compare the two plots before harvesting. In cereal crops such as wheat and paddy, mature plants commonly become golden-yellow and dry, and their grain becomes full and firm. The green plants with soft grain are still immature. Inspect the colour, dryness and grain in both plots.',
  },
  {
    id: 'harvesting',
    title: 'Harvesting the Crop',
    cue: 'Inspect the sickle, cut stalks, gathered bundle and mechanical harvester.',
    detail: 'Harvesting is cutting and gathering a mature crop. A sickle may be used on a small farm, while a harvesting machine can work more quickly over a large area.',
    actionId: 'inspect-harvesting-methods',
    actionLabel: 'Inspect the next harvesting feature',
    evidenceId: 'harvesting-method-evidence',
    evidenceMode: 'scene',
    narrationText: 'Harvesting is the cutting and gathering of a mature crop from the field. Harvesting too early can give immature grain, while waiting too long can allow grain to fall or become damaged. On small farms, a sickle may cut stalks near the ground before they are gathered into bundles. On larger farms, a harvesting machine can complete the work more quickly.',
  },
  {
    id: 'threshing',
    title: 'Threshing Separates the Grain',
    cue: 'Follow attached grain through the thresher and compare the collected grain with the separated straw.',
    detail: 'Threshing separates grain from harvested stalks and other plant material. A combine harvester can harvest and thresh in one operation.',
    actionId: 'operate-threshing-demonstration',
    actionLabel: 'Run the threshing demonstration',
    evidenceId: 'threshing-separation-evidence',
    evidenceMode: 'scene',
    narrationText: 'After harvesting, the grain is still attached to the stalks. Threshing separates the grain from the harvested stalks and other plant material. It may be done manually or with a mechanical thresher. Watch the grain fall into one container while the dry stems move aside. A combine harvester performs harvesting and threshing in one operation.',
  },
  {
    id: 'winnowing',
    title: 'Winnowing and Cleaning',
    cue: 'Start the airflow and observe where the light chaff and heavier grain travel.',
    detail: 'During winnowing, moving air carries lighter chaff farther while heavier grain falls nearby for collection.',
    actionId: 'winnow-grain-and-chaff',
    actionLabel: 'Start the controlled airflow',
    evidenceId: 'winnowing-separation-evidence',
    evidenceMode: 'scene',
    narrationText: 'After threshing, grain may remain mixed with light pieces of husk and chaff. During winnowing, moving air carries the lighter chaff farther away while the heavier grain falls nearby. Start the airflow and collect the cleaned grain in the tray.',
  },
  {
    id: 'drying',
    title: 'Dry the Grains Before Storage',
    cue: 'Compare damp, clumped grain with properly dried, free-flowing grain and inspect the magnified storage view.',
    detail: 'Proper drying lowers grain moisture and reduces the conditions that support fungi, other microorganisms and rotting during storage.',
    actionId: 'compare-damp-and-dry-grain',
    actionLabel: 'Inspect both grain batches',
    evidenceId: 'grain-drying-evidence',
    evidenceMode: 'scene',
    narrationText: 'Freshly harvested grain may contain too much moisture for safe storage. In the damp batch, water helps fungi and other microorganisms grow and the grain can rot. Proper drying lowers the moisture, so the clean grain flows freely and can remain safe for longer. Drying does not sterilise grain, so it must still be inspected and stored correctly.',
  },
  {
    id: 'storage',
    title: 'Store the Crop Safely',
    cue: 'Inspect safe bags, sealed metal bins, a granary and silos, then locate every risk in the damp corner.',
    detail: 'Clean, properly dried grain should be kept in a clean, dry, regularly inspected store protected from moisture, insects, microorganisms, rodents and birds.',
    actionId: 'inspect-safe-and-unsafe-storage',
    actionLabel: 'Inspect the next storage feature',
    evidenceId: 'safe-storage-evidence',
    evidenceMode: 'scene',
    narrationText: 'Stored grain must be protected from moisture, insects, microorganisms, rodents and birds. Smaller quantities may be kept in clean bags on raised platforms or in suitable sealed metal bins. Large quantities may be stored in granaries, warehouses and silos. Keep bags away from damp floors and walls, repair torn bags and inspect the store regularly. Chemical treatment or fumigation must be performed only by trained adults.',
  },
  {
    id: 'summary',
    title: 'Field-to-Storage Summary',
    cue: 'Build the complete sequence from mature crop to protected storage.',
    detail: 'The process is mature crop, harvesting, threshing, winnowing, drying and safe storage. Each step reduces avoidable grain loss.',
    actionId: 'order-field-to-storage-process',
    actionLabel: 'Place the next process step',
    evidenceId: 'field-to-storage-sequence-evidence',
    evidenceMode: 'answer',
    misconceptionId: `${viewerKey}:misconception`,
    narrationText: 'Review the journey. A mature crop is harvested. Threshing separates grain from stalks, and winnowing separates the heavier grain from lighter chaff. The cleaned grain is dried properly, then placed in clean, dry storage protected from moisture and pests. Build the sequence from field to storage.',
  },
  {
    id: 'challenge',
    title: 'Protect the Harvest',
    cue: 'Complete four tasks: select the mature crop, order five processes, activate the correct machine and choose safe storage.',
    detail: 'Choose the golden-yellow dry crop; order harvesting, threshing, winnowing, drying and storage; select the thresher instead of the irrigation pump or seed drill; then choose sealed bins and clean bags on raised platforms instead of open or torn bags beside a damp wall.',
    actionId: 'complete-four-task-harvest-challenge',
    actionLabel: 'Complete the next challenge task',
    evidenceId: 'harvest-protected-evidence',
    evidenceMode: 'answer',
    transferPromptId: `${viewerKey}:transfer`,
    narrationText: 'Now apply everything you learned in four tasks. First, identify the crop that is mature and ready. Second, arrange the five field-to-storage processes in order. Third, choose the machine that separates grain from stalks. Finally, place the dried grain in the safest storage area. Use the evidence from every station to protect the harvest.',
  },
] satisfies GuidedStageAuthoring[];

const { guidance, narration } = createGuidedLesson({
  id: viewerKey,
  moduleId,
  viewerKey,
  classContext: 'CBSE Class 8 Science',
  gradeTone: 'class6To8',
  objective: 'Use visible crop and grain evidence to explain harvesting, threshing, winnowing, drying and safe storage in the correct field-to-store sequence.',
  stages,
  completion: {
    eyebrow: 'Mission complete',
    headline: 'Harvest Saved!',
    body: 'You harvested at maturity, separated and cleaned the grain, dried it properly and protected it in safe storage.',
    actionLabel: 'Review the field-to-storage journey',
  },
});

const assessment = createGuidedAssessment({
  id: `${viewerKey}:assessment`,
  objectiveId: guidance.id,
  misconception: {
    id: `${viewerKey}:misconception`,
    stageId: 'summary',
    question: 'Which field-to-storage sequence is scientifically correct?',
    acceptedEvidenceId: 'field-to-storage-sequence-evidence',
    acceptedLabel: 'Harvesting, threshing, winnowing, drying, then storage.',
    distractorLabel: 'Harvesting, storage, threshing, drying, then winnowing.',
    hint: 'Grain must be detached, cleaned and dried before it enters protected storage.',
    explanation: 'Harvesting comes first; threshing detaches the grain, winnowing removes light chaff, drying lowers moisture, and safe storage comes last.',
  },
  transfer: {
    id: `${viewerKey}:transfer`,
    stageId: 'challenge',
    question: 'Which complete plan best protects cereal grain from field to storage?',
    acceptedEvidenceId: 'harvest-protected-evidence',
    acceptedLabel: 'Harvest the mature crop, thresh, winnow, dry, then use clean protected storage.',
    distractorLabel: 'Harvest the green crop and put damp, uncleaned grain in open bags beside a wall.',
    hint: 'Check crop maturity, the order of separation steps, grain moisture and protection from dampness and pests.',
    explanation: 'Correct timing, separation, cleaning, drying and protected storage work together to reduce grain loss.',
  },
});

export const HARVESTING_THRESHING_STORAGE_GUIDANCE = guidance;
export const HARVESTING_THRESHING_STORAGE_SCENE_METADATA = Object.freeze({
  environmentUrl: `/simulations/${slug}/environment.webp`,
  stageOutcomes: Object.fromEntries(stages.map(stage => [`scene:${stage.id}`, stage.detail])),
});

export const HARVESTING_THRESHING_STORAGE_SIMULATION = defineGuidedImplementedSimulation({
  module: createGuidedModuleRecord({
    id: moduleId,
    title: 'Harvesting, Threshing and Storage of Crops',
    slug,
    viewerKey,
    summary: 'Follow cereal grain from a mature field through harvesting, threshing, winnowing and drying, then protect it from moisture and pests in safe storage.',
    gradeBands: ['class6To8'],
    subjects: ['biology', 'science'],
    curriculumMapIds: ['chapter-cbse-c8-crop-production'],
    conceptIds: [
      'concept-crop-harvest-maturity',
      'concept-threshing-and-winnowing',
      'concept-grain-drying-and-storage',
    ],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'A 360-degree field-to-store journey lets learners compare crop maturity, track two different separation processes and inspect otherwise hidden moisture and pest damage at life-like scale.',
    learningObjective: 'Identify harvest-ready cereal crops, distinguish harvesting, threshing and winnowing, explain why grain is dried, and select storage that limits moisture and pest damage.',
    scientificConceptExplanation: 'Mature cereal crops are harvested; threshing detaches grain from stalks; winnowing uses moving air to separate lighter chaff from heavier grain; drying lowers moisture before clean, protected storage.',
    misconceptionsAddressed: [
      'A green cereal crop with soft grain is ready to harvest.',
      'Threshing and winnowing are two names for the same separation process.',
      'A combine harvester only cuts the crop and cannot thresh it.',
      'Damp grain is safe to store in open bags on a floor.',
      'Drying alone permanently protects grain from every storage pest.',
    ],
    visualizationStrategy: 'A realistic cereal-field panorama transitions through eight evidence-gated stations: maturity comparison, harvesting yard, transparent thresher, winnowing tray, moisture cutaway, storage centre, process summary and four-task challenge.',
    interactionStrategy: 'Learners compare, inspect, activate and sequence visible evidence at each station before completing four linked decisions that protect the harvest.',
    practicalUseCase: 'Connects classroom crop science to recognising maturity, reducing post-harvest loss and keeping household or farm grain clean, dry and protected.',
    cueCardIds: stages.map(stage => `${viewerKey}:cue:${stage.id}`),
    revisionCardIds: [`${viewerKey}:revision`],
    assessmentHookIds: [`${viewerKey}:misconception`, `${viewerKey}:transfer`],
    instructorScript: 'Run the experience as a five-minute field-to-store investigation. Require visible evidence at each station and ask learners to explain the difference between threshing and winnowing before the final four-task challenge.',
    batchActivityPrompt: 'Give groups cards for mature crop, harvesting, threshing, winnowing, drying and storage. Ask them to order the cards and defend one safe storage choice using moisture and pest evidence.',
    expectedDurationMinutes: 5,
    maxSessionDurationMinutes: 8,
    comfortRiskLevel: 'low',
    safetyNotes: [
      'Sickles, threshers and harvesters are interactive models; real cutting tools and farm machinery require trained adult operation and supervision.',
      'Fumigation and other chemical grain treatments must only be performed by trained adults using approved procedures.',
      'Use a stationary or bounded VR area and keep the floor clear before entering immersive mode.',
    ],
    estimatedPackageSizeMb: 8,
  }, guidance),
  guidance,
  assessment,
  narration,
  assets: createGuidedAssetManifest({
    id: `assets:${moduleId}`,
    environment: {
      id: `${moduleId}:field-to-storage-environment`,
      url: `/simulations/${slug}/environment.webp`,
      source: 'OpenAI image generation for the user-authored Harvesting, Threshing and Storage of Crops simulation',
      license: 'project-generated',
      author: 'OpenAI image generation directed by Aditya K. R. Pandey',
      width: 1774,
      height: 887,
      channels: ['baseColor'],
      compression: 'WebP lossy q76; sharp/libvips effort 6',
      byteSize: 231568,
      sha256: '57c7de1632da372ba3c8099d2e049a3980f27bcc5420b8942221b74bb545c246',
    },
  }),
  legacyPaths: [],
  contribution: {
    source: 'user-story',
    integration: 'new-class',
    contributor: 'Aditya K. R. Pandey',
    sourcePath: 'apps/web/components/simulations/HarvestingStorageViewer.tsx',
  },
});
