import {
  createGuidedAssessment,
  createGuidedAssetManifest,
  createGuidedLesson,
  createGuidedModuleRecord,
  defineGuidedImplementedSimulation,
  type GuidedStageAuthoring,
} from './builders.js';

const moduleId = 'sim-c08-ch01-a03-irrigation-methods';
const slug = 'c8-ch01-a03-irrigation-methods';
const viewerKey = 'guided-irrigation-methods';

const stages = [
  {
    id: 'dry-field',
    title: 'A Field in Need of Water',
    cue: 'Inspect the dry soil, drooping crop and nearby water source, then identify irrigation.',
    detail: 'Irrigation is the artificial supply of water to crops at regular intervals according to crop, soil and seasonal needs.',
    actionId: 'identify-irrigation-meaning',
    actionLabel: 'Choose the meaning of irrigation',
    evidenceId: 'irrigation-definition-evidence',
    evidenceMode: 'answer',
    misconceptionId: `${viewerKey}:misconception`,
    narrationText: 'Seeds have germinated and young plants are growing, but the soil is becoming dry. Plants need water at suitable intervals for healthy growth. The artificial supply of water to crops at regular intervals is called irrigation. Inspect the soil, the plants and the available water source.',
  },
  {
    id: 'root-zone',
    title: 'Why Crops Need Irrigation',
    cue: 'Trace water and dissolved minerals from the soil, through the roots and towards the leaves.',
    detail: 'Water supports germination, transports dissolved mineral nutrients, maintains plant cells and is required for photosynthesis.',
    actionId: 'trace-root-water-journey',
    actionLabel: 'Inspect the next root-zone feature',
    evidenceId: 'root-absorption-evidence',
    evidenceMode: 'scene',
    narrationText: 'Water is essential for crop growth. Roots absorb water and dissolved minerals from the soil. Water helps seeds germinate, carries mineral nutrients through the plant, supports photosynthesis and protects crops during hot and dry conditions. Follow the journey from moist soil to root and leaf.',
  },
  {
    id: 'water-sources',
    title: 'Sources of Irrigation Water',
    cue: 'Reveal the well, tube well, pond, river, dam and canal, then follow water towards farmland.',
    detail: 'The available irrigation source depends on local rainfall, groundwater, surface water, storage and distribution systems.',
    actionId: 'inspect-irrigation-water-sources',
    actionLabel: 'Reveal the next water source',
    evidenceId: 'irrigation-source-evidence',
    evidenceMode: 'scene',
    narrationText: 'Irrigation water may come from wells, tube wells, ponds, lakes, rivers, dams and canals. Wells and tube wells use groundwater. Ponds and dams store water. Canals carry water from rivers or reservoirs towards fields. Inspect each source and observe how water reaches farmland.',
  },
  {
    id: 'traditional',
    title: 'Traditional Irrigation Methods',
    cue: 'Operate the moat, dhekli, chain pump and rahat to lift water into field channels.',
    detail: 'Traditional systems are often affordable and locally repairable, but generally require more human or animal effort and time.',
    actionId: 'operate-traditional-irrigation-methods',
    actionLabel: 'Operate the next traditional method',
    evidenceId: 'traditional-irrigation-evidence',
    evidenceMode: 'scene',
    narrationText: 'Traditional methods lift water from wells, ponds or canals. A moat uses a bucket and pulley. A dhekli uses a long lever. A chain pump carries water upward using a moving chain, and a rahat uses a rotating wheel fitted with containers. These methods cost less but usually need more labour and time.',
  },
  {
    id: 'sprinkler',
    title: 'Sprinkler Irrigation System',
    cue: 'Start the pump, connect the pipe and adjust the rotating nozzles until the uneven field is covered.',
    detail: 'Pressurised water travels through pipes and rotating nozzles, falling like rain across uneven or sandy land.',
    actionId: 'configure-sprinkler-irrigation',
    actionLabel: 'Complete the next sprinkler step',
    evidenceId: 'sprinkler-coverage-evidence',
    evidenceMode: 'scene',
    narrationText: 'In sprinkler irrigation, a pump sends water through pipes under pressure. Rotating nozzles spray the water over crops like rainfall. Sprinklers can distribute water across uneven or sandy land and are useful where the available water must cover a broad field.',
  },
  {
    id: 'drip',
    title: 'Drip Irrigation System',
    cue: 'Open the valve, place drippers beside the root zones and adjust a slow, steady flow.',
    detail: 'Drip irrigation applies water drop by drop near individual roots, reducing evaporation, runoff and watering of empty spaces.',
    actionId: 'configure-drip-irrigation',
    actionLabel: 'Complete the next drip step',
    evidenceId: 'drip-root-zone-evidence',
    evidenceMode: 'scene',
    narrationText: 'In drip irrigation, narrow tubes carry water along crop rows. Small outlets release water slowly beside each plant root zone. Very little water is lost by evaporation or runoff, so drip irrigation is highly water efficient for orchards, gardens and water-scarce areas.',
  },
  {
    id: 'compare',
    title: 'Compare the Methods',
    cue: 'Compare labour, land suitability, coverage and water loss for traditional, sprinkler and drip irrigation.',
    detail: 'No single system is best everywhere. A suitable choice matches the crop, terrain, water availability, cost and labour conditions.',
    actionId: 'compare-irrigation-methods',
    actionLabel: 'Compare the next irrigation method',
    evidenceId: 'irrigation-comparison-evidence',
    evidenceMode: 'scene',
    narrationText: 'Different irrigation methods suit different conditions. Traditional methods may be affordable but require more labour. Sprinklers spread water like rain and work well across uneven land. Drip irrigation delivers water directly to roots and usually wastes the least water. Compare all three before choosing.',
  },
  {
    id: 'field-challenge',
    title: 'Choose the Correct Irrigation Method',
    cue: 'Match three real field conditions with the method that supplies water effectively and responsibly.',
    detail: 'Select sprinkler for an uneven broad field, drip for an orchard facing water scarcity, and a traditional lifting method for a small low-budget farm beside a well.',
    actionId: 'match-fields-to-irrigation-methods',
    actionLabel: 'Match the next field',
    evidenceId: 'irrigation-transfer-evidence',
    evidenceMode: 'answer',
    transferPromptId: `${viewerKey}:transfer`,
    narrationText: 'Apply your evidence. Use sprinkler irrigation for the uneven wheat field, drip irrigation for the fruit orchard where water is scarce, and a suitable traditional lifting method for the small farm beside a well with simple equipment. The best method depends on field conditions, crop needs and available water.',
  },
] satisfies GuidedStageAuthoring[];

const { guidance, narration } = createGuidedLesson({
  id: viewerKey,
  moduleId,
  viewerKey,
  classContext: 'CBSE Class 8 Science',
  gradeTone: 'class6To8',
  objective: 'Explain why irrigation is needed, identify water sources and compare traditional, sprinkler and drip systems to choose a suitable method for a field.',
  stages,
  completion: {
    eyebrow: 'Water-wise farmer',
    headline: 'Irrigation Planner Certified',
    body: 'You traced water through roots, operated traditional and modern systems, and matched each field with an appropriate irrigation method.',
    actionLabel: 'Review the irrigation plan',
  },
});

const assessment = createGuidedAssessment({
  id: `${viewerKey}:assessment`,
  objectiveId: guidance.id,
  misconception: {
    id: `${viewerKey}:misconception`,
    stageId: 'dry-field',
    question: 'What does irrigation mean?',
    acceptedEvidenceId: 'irrigation-definition-evidence',
    acceptedLabel: 'Supplying water artificially to crops at suitable regular intervals.',
    distractorLabel: 'Removing weeds and harvesting mature crops from a field.',
    hint: 'Look at the dry soil, drooping crop and nearby water source.',
    explanation: 'Irrigation is the planned artificial supply of water to crops when rainfall or soil moisture is insufficient.',
  },
  transfer: {
    id: `${viewerKey}:transfer`,
    stageId: 'field-challenge',
    question: 'How should a farmer choose an irrigation method?',
    acceptedEvidenceId: 'irrigation-transfer-evidence',
    acceptedLabel: 'Match the method to terrain, crop, water availability, labour and cost.',
    distractorLabel: 'Use the same irrigation method for every crop and every field.',
    hint: 'Compare the uneven field, the orchard and the small farm beside a well.',
    explanation: 'Sprinkler, drip and traditional systems have different strengths, so selection must respond to local field conditions.',
  },
});

export const IRRIGATION_METHODS_GUIDANCE = guidance;
export const IRRIGATION_METHODS_SCENE_METADATA = Object.freeze({
  environmentUrl: `/simulations/${slug}/environment.webp`,
  stageOutcomes: Object.fromEntries(stages.map(stage => [`scene:${stage.id}`, stage.detail])),
});

export const IRRIGATION_METHODS_SIMULATION = defineGuidedImplementedSimulation({
  module: createGuidedModuleRecord({
    id: moduleId,
    title: 'Irrigation Methods: Every Root Gets Water',
    slug,
    viewerKey,
    summary: 'Restore a dry crop field by tracing water from source to root, operating four traditional devices, configuring sprinkler and drip systems, and choosing the right method for three field conditions.',
    gradeBands: ['class6To8'],
    subjects: ['biology', 'science'],
    curriculumMapIds: ['chapter-cbse-c8-crop-production'],
    conceptIds: ['concept-irrigation', 'concept-irrigation-water-sources', 'concept-irrigation-method-selection'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'Spatial interaction lets learners operate lifting devices, see pressurised coverage and inspect underground root wetting that are difficult to compare simultaneously in a classroom.',
    learningObjective: 'Define irrigation, explain its importance, identify common water sources, compare traditional and modern methods, and select a suitable system for a field.',
    scientificConceptExplanation: 'Irrigation supplies crop water at suitable intervals. Traditional devices lift water mechanically, sprinklers distribute pressurised water over an area, and drip systems release small amounts close to roots.',
    misconceptionsAddressed: [
      'Irrigation means removing weeds or harvesting crops.',
      'Leaves are the main plant part that absorbs water from soil.',
      'The same irrigation method is suitable for every field.',
      'Sprinkler and drip irrigation deliver water in the same way.',
    ],
    visualizationStrategy: 'A realistic Indian farm panorama supports eight procedural stations: dry field, root cutaway, source map, traditional lifting yard, sprinkler field, drip orchard, comparison plots and a holographic field-planning challenge.',
    interactionStrategy: 'Learners inspect crop evidence, reveal water sources, operate four traditional devices, configure pressurised and drip networks, compare water use and match methods to field conditions.',
    practicalUseCase: 'Connects crop science with local water sources, farm labour, terrain, water conservation and responsible agricultural planning.',
    cueCardIds: stages.map(stage => `${viewerKey}:cue:${stage.id}`),
    revisionCardIds: [`${viewerKey}:revision`],
    assessmentHookIds: [`${viewerKey}:misconception`, `${viewerKey}:transfer`],
    instructorScript: 'Run the experience as a five-minute farm investigation. Ask learners to justify why each system is suitable before accepting the final three field matches.',
    batchActivityPrompt: 'Give groups three field cards and three irrigation cards. Require each group to defend its matches using terrain, water loss, labour and crop evidence.',
    expectedDurationMinutes: 5,
    maxSessionDurationMinutes: 9,
    comfortRiskLevel: 'low',
    safetyNotes: [
      'All pumps, wells and water-lifting devices are interactive models; learners should never operate real farm machinery without trained adult supervision.',
      'Use a stationary or bounded VR area and keep the floor clear before entering immersive mode.',
      'Water coverage and underground wetting are simplified teaching visualisations rather than engineering design calculations.',
    ],
    estimatedPackageSizeMb: 10,
  }, guidance),
  guidance,
  assessment,
  narration,
  assets: createGuidedAssetManifest({
    id: `assets:${moduleId}`,
    environment: {
      id: `${moduleId}:irrigation-farm-environment`,
      url: `/simulations/${slug}/environment.webp`,
      source: 'OpenAI image generation for the user-authored Irrigation Methods simulation',
      license: 'project-generated',
      author: 'OpenAI image generation directed by Aditya K. R. Pandey',
      width: 1774,
      height: 887,
      channels: ['baseColor'],
      compression: 'WebP lossy q76; sharp/libvips effort 6',
      byteSize: 313990,
      sha256: '680c60dba22e4c6c521af92327615fe1dd1bf53944fe4c8741006dfc4cf68ba2',
    },
  }),
  legacyPaths: [],
  contribution: {
    source: 'user-story',
    integration: 'new-class',
    contributor: 'Aditya K. R. Pandey',
    sourcePath: 'apps/web/components/simulations/IrrigationMethodsViewer.tsx',
  },
});
