import {
  createGuidedAssessment,
  createGuidedAssetManifest,
  createGuidedLesson,
  createGuidedModuleRecord,
  defineGuidedImplementedSimulation,
  type GuidedStageAuthoring,
} from './builders.js';

const moduleId = 'sim-c07-ch03-a01-shearing-and-scouring-of-wool';
const slug = 'c7-ch03-a01-shearing-and-scouring-of-wool';
const viewerKey = 'guided-shearing-scouring-wool';

const stages = [
  {
    id: 'arrival',
    title: 'Meet Woolly in Flock Valley',
    cue: 'Touch the springy fleece, scan its temperature and inspect the fibres.',
    detail: 'The thick coat of hair covering a sheep is called its fleece. It traps still air and helps the animal stay warm in winter.',
    actionId: 'inspect-woolly-fleece',
    actionLabel: 'Explore Woolly',
    evidenceId: 'fleece-inspection-evidence',
    evidenceMode: 'scene',
    narrationText: 'Welcome to Flock Valley, Young Wool Scientist. Meet Woolly. His thick fleece protected him in winter, but warm weather has arrived. Touch the fleece, scan its temperature, and look closely at the fibres.',
  },
  {
    id: 'season',
    title: 'Choose the Safe Season',
    cue: 'Decide when Woolly can be sheared without losing his winter protection.',
    detail: 'Sheep are generally sheared during warm weather while the fleece is dry. This keeps them comfortable and allows the coat to regrow before winter.',
    actionId: 'select-summer-season',
    actionLabel: 'Choose summer',
    evidenceId: 'safe-season-evidence',
    evidenceMode: 'scene',
    narrationText: 'Choose the safe season for shearing. Winter fleece protects the sheep from cold, and wet fleece is difficult to process. Warm, dry summer weather is the suitable choice.',
  },
  {
    id: 'prepare',
    title: 'Prepare the Shearing Station',
    cue: 'Keep Woolly dry and calm, then choose clean, inspected electric shears.',
    detail: 'A trained shearer uses clean, suitable equipment on a dry sheep standing or resting on a clean, non-slip surface.',
    actionId: 'prepare-clean-shears',
    actionLabel: 'Prepare clean shears',
    evidenceId: 'safe-equipment-evidence',
    evidenceMode: 'scene',
    narrationText: 'Prepare the station carefully. Woolly must be dry and calm on a clean non-slip surface. Inspect and oil the clean electric shears. A kitchen knife or dirty tool is unsafe.',
  },
  {
    id: 'shearing',
    title: 'Shear Along the Guide Lines',
    cue: 'Use smooth, steady passes and keep the shears almost parallel to the skin.',
    detail: 'Shearing is the careful removal of a sheep\'s fleece. A trained person handles the sheep gently and removes the fleece without cutting the skin.',
    actionId: 'complete-safe-shearing',
    actionLabel: 'Make a steady pass',
    evidenceId: 'safe-shearing-evidence',
    evidenceMode: 'scene',
    narrationText: 'The removal of fleece is called shearing. Follow the blue guide lines with slow, smooth passes. Keep the shears almost parallel to the skin and never rush across folds in the skin.',
  },
  {
    id: 'detect',
    title: 'Become a Fibre Detective',
    cue: 'Find dust, sweat, plant pieces and the natural grease called lanolin.',
    detail: 'Raw fleece is yellowish, sticky and heavy because material from the sheep and its surroundings remains trapped between the fibres.',
    actionId: 'scan-raw-fleece',
    actionLabel: 'Scan all four impurities',
    evidenceId: 'raw-fleece-needs-cleaning',
    evidenceMode: 'answer',
    misconceptionId: `${viewerKey}:misconception`,
    narrationText: 'The fleece has been removed, but it is not ready for spinning. Use the magnifier to find dust and soil, sweat, grass pieces, and lanolin, the natural grease that protects the sheep\'s skin and fleece.',
  },
  {
    id: 'experiment',
    title: 'Test Three Washing Methods',
    cue: 'Compare cold water, controlled warm cleaning and very hot rough washing.',
    detail: 'Water alone leaves grease behind. Excessive heat and rough movement can mat the fibres. Controlled warmth, a suitable cleaner and gentle movement remove impurities safely.',
    actionId: 'choose-controlled-wash',
    actionLabel: 'Choose container B',
    evidenceId: 'controlled-scouring-evidence',
    evidenceMode: 'scene',
    narrationText: 'Test three cleaning methods. Cold water removes some dust but leaves grease. Very hot water and rough movement can mat wool. Controlled warm water with a suitable cleaner works best.',
  },
  {
    id: 'scour',
    title: 'Operate the Scouring Station',
    cue: 'Set the temperature, add cleaner, wash gently, rinse twice, roll and dry.',
    detail: 'Scouring is the thorough washing of sheared wool to remove dirt, dust, sweat and grease without tangling the fibres.',
    actionId: 'complete-scouring-cycle',
    actionLabel: 'Run the next scouring step',
    evidenceId: 'clean-scoured-wool-evidence',
    evidenceMode: 'scene',
    narrationText: 'Now operate the scouring station. Set controlled warmth, add the correct amount of cleaner, wash gently, rinse until the water stays clear, squeeze with rollers, and spread the wool to dry.',
  },
  {
    id: 'compare',
    title: 'Compare Before and After',
    cue: 'Inspect the raw fleece beside the clean, dry scoured wool.',
    detail: 'Raw fleece is greasy, dirty, yellowish and heavy. Scoured wool is cleaner, softer, lighter and ready for the next processing stage.',
    actionId: 'compare-wool-samples',
    actionLabel: 'Inspect both samples',
    evidenceId: 'before-after-comparison-evidence',
    evidenceMode: 'scene',
    narrationText: 'Compare the samples. Raw fleece is greasy, sticky and heavy. Scoured wool is clean, soft, lighter and fluffy because dirt, sweat and grease have been removed.',
  },
  {
    id: 'sequence',
    title: 'Build the Wool Journey',
    cue: 'Place six stages from sheep with fleece to clean wool drying on a rack.',
    detail: 'The correct sequence is fleece on sheep, shearing, raw fleece collection, scouring, rinsing and drying.',
    actionId: 'order-wool-journey',
    actionLabel: 'Place the next process step',
    evidenceId: 'wool-sequence-evidence',
    evidenceMode: 'scene',
    narrationText: 'Build the wool journey in order: sheep with fleece, shearing, raw fleece collection, scouring, rinsing, and drying. Each stage prepares the fibre for what comes next.',
  },
  {
    id: 'challenge',
    title: 'Earn the Master of Wool Badge',
    cue: 'Apply the difference between shearing and scouring in the final challenge.',
    detail: 'Shearing removes fleece from the sheep. Scouring cleans the removed fleece. Both require scientific knowledge, skill and humane animal care.',
    actionId: 'complete-wool-challenge',
    actionLabel: 'Answer the rapid challenge',
    evidenceId: 'wool-process-transfer-evidence',
    evidenceMode: 'answer',
    transferPromptId: `${viewerKey}:transfer`,
    narrationText: 'Complete the mission. Shearing means carefully removing the fleece. Scouring means cleaning that fleece. Sheep must be handled gently, and clean wool is then ready for later processing into yarn and fabric.',
  },
] satisfies GuidedStageAuthoring[];

const { guidance, narration } = createGuidedLesson({
  id: viewerKey,
  moduleId,
  viewerKey,
  classContext: 'CBSE Class 7 Science',
  gradeTone: 'class6To8',
  objective: 'Safely distinguish shearing from scouring by inspecting fleece, choosing suitable conditions and equipment, and completing the wool-cleaning sequence.',
  stages,
  completion: {
    eyebrow: 'Mission accomplished',
    headline: 'Master of Wool Processing',
    body: 'You protected Woolly, removed the fleece safely, identified its impurities and completed a controlled scouring cycle.',
    actionLabel: 'Review the wool journey',
  },
});

const assessment = createGuidedAssessment({
  id: `${viewerKey}:assessment`,
  objectiveId: guidance.id,
  misconception: {
    id: `${viewerKey}:misconception`,
    stageId: 'detect',
    question: 'Can dirty, greasy raw fleece be spun directly into yarn?',
    acceptedEvidenceId: 'raw-fleece-needs-cleaning',
    acceptedLabel: 'No. It must be scoured first.',
    distractorLabel: 'Yes. Spin it immediately.',
    hint: 'Look again for lanolin, sweat, dust and plant pieces trapped in the fleece.',
    explanation: 'Raw fleece must be scoured so dirt, sweat and grease are removed before later processing.',
  },
  transfer: {
    id: `${viewerKey}:transfer`,
    stageId: 'challenge',
    question: 'Which statement correctly distinguishes the two processes?',
    acceptedEvidenceId: 'wool-process-transfer-evidence',
    acceptedLabel: 'Shearing removes fleece; scouring cleans it.',
    distractorLabel: 'Scouring removes fleece; shearing cleans it.',
    hint: 'Think about what happens first while the fleece is still on Woolly.',
    explanation: 'A trained shearer removes the fleece first. The removed fleece is then scoured to clean it.',
  },
});

export const SHEARING_SCOURING_WOOL_GUIDANCE = guidance;
export const SHEARING_SCOURING_WOOL_SCENE_METADATA = Object.freeze({
  environmentUrl: `/simulations/${slug}/environment.webp`,
  stageOutcomes: Object.fromEntries(stages.map(stage => [`scene:${stage.id}`, stage.detail])),
});

export const SHEARING_SCOURING_WOOL_SIMULATION = defineGuidedImplementedSimulation({
  module: createGuidedModuleRecord({
    id: moduleId,
    title: 'Shearing and Scouring of Wool',
    slug,
    viewerKey,
    legacyAliases: ['fibre-to-fabric-shearing-scouring'],
    summary: 'Mission Wool: care for Woolly, remove the fleece safely, detect impurities and clean the fibre through controlled scouring.',
    gradeBands: ['class6To8'],
    subjects: ['biology', 'science'],
    curriculumMapIds: ['cm-cbse-c7-ch03-wool-processing'],
    conceptIds: ['concept-shearing-scouring-wool'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'VR makes animal-scale inspection, safe tool posture, fibre comparison and the multi-station cleaning sequence spatially understandable without exposing students or animals to risk.',
    learningObjective: 'Distinguish shearing from scouring and explain the safe conditions, equipment and ordered steps used to obtain clean wool.',
    scientificConceptExplanation: 'Shearing carefully removes dry fleece during suitable warm weather; scouring uses controlled warm water, a suitable cleaning solution and gentle handling to remove dirt, sweat and lanolin.',
    misconceptionsAddressed: [
      'Raw fleece can be spun directly without cleaning.',
      'Shearing and scouring are the same process.',
      'Very hot water and rough movement clean wool best.',
    ],
    visualizationStrategy: 'A realistic pasture transitions through a shearing station, fibre inspection bench, three-container experiment, working scouring line and process timeline.',
    interactionStrategy: 'Learners inspect, choose, sequence and operate one evidence-gated action at a time using responsive browser controls or Quest controller input.',
    practicalUseCase: 'Connects the origin of woollen clothing with humane animal care and controlled fibre processing.',
    cueCardIds: stages.map(stage => `${viewerKey}:cue:${stage.id}`),
    revisionCardIds: [`${viewerKey}:revision`],
    assessmentHookIds: [`${viewerKey}:misconception`, `${viewerKey}:transfer`],
    instructorScript: 'Ask learners to predict each safe choice, name the visible evidence and explain why the rejected method could harm the sheep or fibres.',
    batchActivityPrompt: 'In pairs, reconstruct the six-step wool journey and use the words fleece, shearing, lanolin, scouring, rinsing and drying accurately.',
    expectedDurationMinutes: 10,
    maxSessionDurationMinutes: 14,
    comfortRiskLevel: 'low',
    safetyNotes: [
      'This is an educational simulation; real shearing must only be carried out by trained people using suitable equipment and humane handling.',
      'Do not use blades, hot water or cleaning chemicals without trained adult supervision.',
    ],
    estimatedPackageSizeMb: 8,
  }, guidance),
  guidance,
  assessment,
  narration,
  assets: createGuidedAssetManifest({
    id: `assets:${moduleId}`,
    environment: {
      id: `${moduleId}:flock-valley-environment`,
      url: `/simulations/${slug}/environment.webp`,
      source: 'OpenAI image generation for the user-authored Mission Wool simulation',
      license: 'project-generated',
      author: 'OpenAI image generation directed by Aditya K. R. Pandey',
      width: 1774,
      height: 887,
      channels: ['baseColor'],
      compression: 'WebP lossy q75; sharp/libvips effort 6',
      byteSize: 223608,
      sha256: 'b6fbf1f6230ca9655e7cab247436c9fed4cbf4e6a071e9ce7179746ec232c37f',
    },
  }),
  legacyPaths: ['/simulations/fibre-to-fabric-shearing-scouring'],
  contribution: {
    source: 'user-story',
    integration: 'new-class',
    contributor: 'Aditya K. R. Pandey',
    sourcePath: 'apps/web/components/simulations/WoolProcessingViewer.tsx',
  },
});
