import {
  createGuidedAssessment,
  createGuidedAssetManifest,
  createGuidedLesson,
  createGuidedModuleRecord,
  defineGuidedImplementedSimulation,
  type GuidedStageAuthoring,
} from './builders.js';

const moduleId = 'sim-c08-ch02-a02-virus-introduction-spreading-and-its-effects';
const slug = 'c8-ch02-a02-virus-introduction-spreading-and-its-effects';
const viewerKey = 'guided-virus-invasion';

const stages = [
  {
    id: 'warning',
    title: 'The Invisible Warning',
    cue: 'Activate the micro-scanner and shrink into a world too small for an ordinary school microscope.',
    detail: 'Viruses are extremely small infectious agents. This scientific model enlarges them so their parts and behaviour can be investigated safely.',
    actionId: 'activate-virus-micro-scanner',
    actionLabel: 'Activate micro-scanner',
    evidenceId: 'virus-scale-evidence',
    evidenceMode: 'scene',
    narrationText: 'An invisible infectious agent has been detected. It is too small to be seen with an ordinary school microscope. Activate the micro-scanner and enter its microscopic world.',
  },
  {
    id: 'anatomy',
    title: 'Meet the Virus',
    cue: 'Inspect the genetic material, protein coat, envelope and attachment structures.',
    detail: 'A virus is not a complete cell. Its genetic instructions are protected by a protein coat, and some viruses also have an outer envelope.',
    actionId: 'inspect-virus-structure',
    actionLabel: 'Scan next virus part',
    evidenceId: 'virus-structure-evidence',
    evidenceMode: 'scene',
    narrationText: 'This is a virus, an extremely small infectious agent. It is not a complete cell. Genetic material at the centre carries instructions. A protein coat protects it, some viruses have an envelope, and surface structures help it attach to a suitable living cell. A virus cannot reproduce independently.',
  },
  {
    id: 'replication',
    title: 'Inside the Host Cell',
    cue: 'Run the five-stage cycle: attachment, entry, copying, assembly and release.',
    detail: 'A virus becomes active only after entering a suitable living host cell and using some of that cell\'s machinery to make viral material.',
    actionId: 'run-virus-replication-cycle',
    actionLabel: 'Run next replication stage',
    evidenceId: 'virus-replication-evidence',
    evidenceMode: 'scene',
    narrationText: 'First, the virus attaches to a matching receptor. Next, it enters or releases its genetic material. The viral instructions take control of some cell machinery. New viral material and proteins are copied, assembled into complete particles, and released. One virus has become many.',
  },
  {
    id: 'transmission',
    title: 'The Transmission Tunnel',
    cue: 'Reveal five routes that can move viruses from one host to another.',
    detail: 'Different viruses use different routes. The model includes respiratory particles, hands and surfaces, food or water, insect vectors, and blood or body fluids.',
    actionId: 'inspect-virus-transmission-routes',
    actionLabel: 'Reveal next route',
    evidenceId: 'virus-transmission-evidence',
    evidenceMode: 'scene',
    narrationText: 'Viruses can spread by different routes. Some travel in respiratory particles. Some may transfer from contaminated surfaces to the hands and then the eyes, nose or mouth. Others spread through contaminated food or water, insect vectors such as certain mosquitoes, or infected blood and body fluids.',
  },
  {
    id: 'effects',
    title: 'Effects and Prevention',
    cue: 'Inspect the body systems, then choose actions that reduce viral transmission.',
    detail: 'Viruses damage suitable cells and the immune system responds. Prevention depends on the route: hygiene, ventilation, safe food and water, vector control and recommended vaccination.',
    actionId: 'build-virus-protection-shield',
    actionLabel: 'Add next protection layer',
    evidenceId: 'virus-prevention-evidence',
    evidenceMode: 'answer',
    misconceptionId: `${viewerKey}:misconception`,
    narrationText: 'Viral infections may cause fever, tiredness, cough, sore throat, body ache, rash or digestive problems. Handwashing, covered coughs, ventilation, safe food and water, mosquito control and recommended vaccination can reduce transmission. Vaccines prepare the immune system to recognise particular viruses. Antibiotics work against certain bacteria; they do not cure viral infections.',
  },
  {
    id: 'summary',
    title: 'Rebuild the Viral Cycle',
    cue: 'Place the five replication stages in the scientifically correct order.',
    detail: 'A virus needs a living host cell. Attachment and entry come before copying and assembly; release allows the infection to continue to nearby cells.',
    actionId: 'order-virus-replication-stages',
    actionLabel: 'Place next cycle stage',
    evidenceId: 'virus-cycle-sequence-evidence',
    evidenceMode: 'scene',
    narrationText: 'Review the evidence. A virus needs a living host cell to reproduce. It attaches, enters, uses the cell to copy viral material, assembles new particles and releases them. Different routes can carry viruses to new hosts.',
  },
  {
    id: 'break-chain',
    title: 'Break the Viral Chain',
    cue: 'Match all five transmission risks with the preventive action that controls them.',
    detail: 'The strongest defence is a correct match between a real transmission route and a practical preventive action.',
    actionId: 'complete-break-viral-chain-challenge',
    actionLabel: 'Match next risk',
    evidenceId: 'viral-chain-broken-evidence',
    evidenceMode: 'answer',
    transferPromptId: `${viewerKey}:transfer`,
    narrationText: 'Complete the final challenge. Match respiratory particles with covered coughs, contaminated hands with soap and water, unsafe water with safe drinking water, stagnant water with mosquito control, and closed rooms with ventilation. Understand the spread, protect health and break the chain.',
  },
] satisfies GuidedStageAuthoring[];

const { guidance, narration } = createGuidedLesson({
  id: viewerKey,
  moduleId,
  viewerKey,
  classContext: 'CBSE Class 8 Science',
  gradeTone: 'class6To8',
  objective: 'Explain how viruses depend on host cells, identify major transmission routes and select preventive actions that break the viral chain.',
  stages,
  completion: {
    eyebrow: 'Mission accomplished',
    headline: 'Virus Shield Activated',
    body: 'You inspected viral structure, rebuilt the host-cell cycle and controlled five transmission risks using evidence-based preventive actions.',
    actionLabel: 'Review the viral chain',
  },
});

const assessment = createGuidedAssessment({
  id: `${viewerKey}:assessment`,
  objectiveId: guidance.id,
  misconception: {
    id: `${viewerKey}:misconception`,
    stageId: 'effects',
    question: 'Which statement about antibiotics and viral infections is scientifically correct?',
    acceptedEvidenceId: 'virus-prevention-evidence',
    acceptedLabel: 'Antibiotics act against certain bacteria; they do not cure viral infections.',
    distractorLabel: 'Antibiotics kill every virus and cure viral infections.',
    hint: 'Compare a virus with a bacterium and listen to the prevention narration again.',
    explanation: 'Antibiotics target features of certain bacteria. Viruses reproduce inside host cells and are not cured by antibiotics.',
  },
  transfer: {
    id: `${viewerKey}:transfer`,
    stageId: 'break-chain',
    question: 'What is the best way to break a viral transmission chain?',
    acceptedEvidenceId: 'viral-chain-broken-evidence',
    acceptedLabel: 'Match preventive actions to the route the virus uses to spread.',
    distractorLabel: 'Use the same single action for every virus and every route.',
    hint: 'Respiratory particles, unsafe water and mosquitoes are controlled in different ways.',
    explanation: 'Effective prevention targets the relevant route: hygiene, ventilation, safe water, mosquito control, sterile equipment or vaccination as appropriate.',
  },
});

export const VIRUS_INVASION_GUIDANCE = guidance;
export const VIRUS_INVASION_SCENE_METADATA = Object.freeze({
  environmentUrl: `/simulations/${slug}/environment.webp`,
  stageOutcomes: Object.fromEntries(stages.map(stage => [`scene:${stage.id}`, stage.detail])),
});

export const VIRUS_INVASION_SIMULATION = defineGuidedImplementedSimulation({
  module: createGuidedModuleRecord({
    id: moduleId,
    title: 'The Invisible Invader: Break the Viral Chain',
    slug,
    viewerKey,
    summary: 'Shrink into a virus laboratory, inspect viral structure and host-cell replication, then stop five transmission routes in a timed Class 8 mission.',
    gradeBands: ['class6To8'],
    subjects: ['biology', 'science'],
    curriculumMapIds: ['cm-cbse-c8-ch02-microorganisms'],
    conceptIds: ['concept-virus-structure', 'concept-virus-replication', 'concept-virus-transmission-prevention'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'Immersive scale change makes invisible viral structure and host-cell replication spatially understandable, while a 360-degree transmission tunnel supports route-to-prevention matching without exposure to biological risk.',
    learningObjective: 'Explain why viruses need living host cells, order the main stages of viral replication, recognise transmission routes and apply suitable preventive actions.',
    scientificConceptExplanation: 'Viruses contain genetic material protected by a protein coat, cannot reproduce independently, use suitable host cells to copy and assemble new particles, and spread through routes controlled by route-specific preventive actions.',
    misconceptionsAddressed: [
      'A virus is a complete living cell that reproduces independently.',
      'All viruses spread through the same route.',
      'Antibiotics cure viral infections.',
      'One preventive action is enough for every viral disease.',
    ],
    visualizationStrategy: 'A realistic empty virology laboratory transitions into an enlarged layered virus, a transparent host cell, five transmission alcoves, an anatomical effects model and a complete protection shield.',
    interactionStrategy: 'Learners scan virus parts, advance the five-stage host-cell cycle, reveal transmission routes, build a prevention shield, order replication and match five risks to suitable controls.',
    practicalUseCase: 'Connects viral science to handwashing, cough hygiene, ventilation, clean food and water, mosquito control, sterile equipment and recommended vaccination.',
    cueCardIds: stages.map(stage => `${viewerKey}:cue:${stage.id}`),
    revisionCardIds: [`${viewerKey}:revision`],
    assessmentHookIds: [`${viewerKey}:misconception`, `${viewerKey}:transfer`],
    instructorScript: 'Run the experience as a five-minute guided investigation. Pause after replication and transmission to ask learners for evidence, and finish by requiring each risk-to-prevention match to be explained aloud.',
    batchActivityPrompt: 'In groups, assign five route cards and five prevention cards. Ask learners to justify every match, then reconstruct attachment, entry, copying, assembly and release in order.',
    expectedDurationMinutes: 5,
    maxSessionDurationMinutes: 8,
    comfortRiskLevel: 'low',
    safetyNotes: [
      'All virus, cell and body views are enlarged educational models rather than literal scale.',
      'The experience gives general prevention education and does not diagnose or replace medical advice.',
      'Use a stationary or bounded VR area and keep the floor clear before entering immersive mode.',
    ],
    estimatedPackageSizeMb: 9,
  }, guidance),
  guidance,
  assessment,
  narration,
  assets: createGuidedAssetManifest({
    id: `assets:${moduleId}`,
    environment: {
      id: `${moduleId}:virology-laboratory-environment`,
      url: `/simulations/${slug}/environment.webp`,
      source: 'OpenAI image generation for the user-authored Invisible Invader simulation',
      license: 'project-generated',
      author: 'OpenAI image generation directed by Aditya K. R. Pandey',
      width: 1774,
      height: 887,
      channels: ['baseColor'],
      compression: 'WebP lossy q76; sharp/libvips effort 6',
      byteSize: 151920,
      sha256: '619cbf4e6176e603b4e816bd76cdff8072484dc32146f6ff40f172b2fabd3f4c',
    },
  }),
  legacyPaths: [],
  contribution: {
    source: 'user-story',
    integration: 'new-class',
    contributor: 'Aditya K. R. Pandey',
    sourcePath: 'apps/web/components/simulations/VirusInvasionViewer.tsx',
  },
});
