import {
  BROWSER_BALANCED_PROFILE,
  BROWSER_ENHANCED_PROFILE,
  QUEST_BASELINE_PROFILE,
  type WorldBundle,
} from '../../../../packages/simulation-schema/src/index';

export const DIAGNOSTIC_WORLD: WorldBundle = {
  world: {
    id: 'world-builder-diagnostic',
    version: '1.0.0',
    title: 'World Builder Material & Mastery Diagnostic',
    metersPerWorldUnit: 1,
    environmentId: 'environment-diagnostic-studio',
    qualityProfileIds: [
      'questBaseline',
      'browserBalanced',
      'browserEnhanced',
    ],
    entityIds: [
      'entity-floor',
      'entity-painted-sphere',
      'entity-metal-sphere',
    ],
    systemIds: ['physics', 'presentation'],
    scientificModelIds: ['model-material-mass'],
    lessonSequenceId: 'lesson-material-evidence',
    assessmentSequenceId: 'assessment-material-evidence',
    assetManifestId: 'assets-diagnostic',
    acceptanceProfileId: 'acceptance-diagnostic',
  },
  entities: [
    {
      id: 'entity-floor',
      visualId: 'visual-floor',
      transform: {
        position: [0, 0, -1.4],
        rotation: [-Math.PI / 2, 0, 0],
        scale: [1, 1, 1],
      },
      materialId: 'material-floor',
      interactionTags: [],
      accessibilityLabel: 'Mapped stone demonstration floor',
    },
    {
      id: 'entity-painted-sphere',
      visualId: 'visual-painted-sphere',
      transform: {
        position: [-0.85, 1.25, -1.4],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
      },
      materialId: 'material-painted',
      colliderId: 'collider-painted-sphere',
      interactionTags: ['selectable', 'physics'],
      accessibilityLabel: 'Teal painted sphere',
    },
    {
      id: 'entity-metal-sphere',
      visualId: 'visual-metal-sphere',
      transform: {
        position: [0.9, 0.72, -1.4],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
      },
      materialId: 'material-metal',
      interactionTags: ['selectable'],
      accessibilityLabel: 'Brushed metal sphere',
    },
  ],
  environments: [{
    id: 'environment-diagnostic-studio',
    background: { kind: 'color', value: '#071014' },
    environmentMap: 'environment-studio',
    fog: { color: '#071014', near: 8, far: 22 },
    keyLight: {
      kind: 'directional',
      color: '#fff4df',
      intensity: 3.2,
      position: [3.5, 6, 3],
      target: [0, 0.9, -1.4],
      castsShadow: true,
    },
    fillLight: {
      kind: 'hemisphere',
      color: '#9adce7',
      intensity: 1.15,
      position: [0, 4, 0],
    },
    accentLights: [{
      kind: 'point',
      color: '#77d8d4',
      intensity: 10,
      position: [-3, 2.4, -3],
      range: 7,
      decay: 2,
    }],
    shadowCasters: ['entity-painted-sphere', 'entity-metal-sphere'],
    exposure: 1.05,
    toneMapping: 'AgX',
  }],
  materials: [
    {
      id: 'material-floor',
      model: 'standard',
      baseColor: '#68767a',
      baseColorMap: 'floor-base-color',
      normalMap: 'floor-normal',
      normalScale: [0.42, 0.42],
      textureRepeat: [5, 5],
      roughness: 0.84,
      roughnessMap: 'floor-roughness',
      metalness: 0,
    },
    {
      id: 'material-painted',
      model: 'standard',
      baseColor: '#4bc4bd',
      roughness: 0.32,
      metalness: 0.03,
    },
    {
      id: 'material-metal',
      model: 'physical',
      baseColor: '#b9c7ca',
      roughness: 0.18,
      metalness: 0.96,
      clearcoat: 0.28,
      fallbackMaterialId: 'material-metal-quest',
    },
    {
      id: 'material-metal-quest',
      model: 'standard',
      baseColor: '#aebfc3',
      roughness: 0.24,
      metalness: 0.92,
    },
  ],
  qualityProfiles: [
    QUEST_BASELINE_PROFILE,
    BROWSER_BALANCED_PROFILE,
    BROWSER_ENHANCED_PROFILE,
  ],
  scientificModels: [{
    id: 'model-material-mass',
    version: '1.0.0',
    domain: 'classification',
    internalUnits: { mass: 'kg' },
    validInputRanges: {
      initialMassKg: { min: 0.01, max: 100, unit: 'kg' },
    },
    assumptions: ['Appearance changes do not replace the selected physical material'],
    limitations: ['Diagnostic identity model; no chemical transformation'],
    referenceSources: ['XR School W0 world-builder specification'],
    referenceVectors: [{
      id: 'appearance-does-not-change-mass',
      inputs: { initialMassKg: 1 },
      expectedOutputs: { finalMassKg: 1 },
    }],
    numericalTolerance: 1e-9,
  }],
  assessments: [{
    id: 'assessment-material-evidence',
    objectiveId: 'objective-separate-appearance-from-mass',
    prompts: [
      {
        id: 'observe',
        kind: 'observation',
        stageId: 'stage-material-comparison',
        question: 'Which sphere is moving under gravity?',
        options: [
          { id: 'painted', label: 'The teal painted sphere' },
          { id: 'metal', label: 'The metal sphere' },
        ],
        acceptedEvidenceIds: ['painted'],
        hint: 'Watch which sphere settles onto the floor.',
        explanation: 'The teal sphere moves and settles while the comparison sphere stays fixed.',
        retryPolicy: 'immediateWithHint',
      },
      {
        id: 'misconception',
        kind: 'misconception',
        stageId: 'stage-material-comparison',
        question: 'Does changing surface color by itself change an object’s mass?',
        options: [
          { id: 'yes', label: 'Yes' },
          { id: 'no', label: 'No' },
        ],
        acceptedEvidenceIds: ['no'],
        hint: 'Color describes appearance, not how much matter is present.',
        explanation: 'A surface color change does not by itself change mass.',
        retryPolicy: 'afterObservation',
      },
      {
        id: 'transfer',
        kind: 'transfer',
        stageId: 'stage-material-comparison',
        question: 'If the same ball is painted red, what happens to its mass?',
        options: [
          { id: 'same', label: 'It stays the same' },
          { id: 'greater', label: 'It becomes greater' },
        ],
        acceptedEvidenceIds: ['same'],
        hint: 'Apply the same evidence to a new paint color.',
        explanation: 'Changing only paint color leaves the ball’s mass unchanged.',
        retryPolicy: 'immediateWithHint',
      },
    ],
    masteryRule: {
      requiredEvidenceCount: 3,
      requiredKinds: ['observation', 'misconception', 'transfer'],
      allowHintedMastery: true,
    },
  }],
  assetManifests: [{
    id: 'assets-diagnostic',
    assets: [
      {
        id: 'floor-base-color',
        url: '/world-builder/floor-base-color.svg',
        kind: 'texture',
        source: 'XR School procedural studio stone',
        license: 'XR School self-authored; redistribution permitted',
        author: 'XR School',
        width: 512,
        height: 512,
        channels: ['baseColor'],
        compression: 'SVG procedural',
      },
      {
        id: 'floor-normal',
        url: '/world-builder/floor-normal.svg',
        kind: 'texture',
        source: 'XR School procedural studio stone',
        license: 'XR School self-authored; redistribution permitted',
        author: 'XR School',
        width: 512,
        height: 512,
        channels: ['normal'],
        compression: 'SVG procedural',
      },
      {
        id: 'floor-roughness',
        url: '/world-builder/floor-roughness.svg',
        kind: 'texture',
        source: 'XR School procedural studio stone',
        license: 'XR School self-authored; redistribution permitted',
        author: 'XR School',
        width: 512,
        height: 512,
        channels: ['roughness'],
        compression: 'SVG procedural',
      },
      {
        id: 'environment-studio',
        url: '/world-builder/studio-environment.svg',
        kind: 'environment',
        source: 'XR School procedural lighting environment',
        license: 'XR School self-authored; redistribution permitted',
        author: 'XR School',
        width: 1024,
        height: 512,
        channels: ['baseColor'],
        compression: 'SVG procedural',
      },
    ],
  }],
  acceptanceProfiles: [{
    id: 'acceptance-diagnostic',
    requiredQualityProfileId: 'questBaseline',
    minSteadyFps: 72,
    maxDrawCalls: 120,
    maxVisibleTriangles: 250_000,
    requiresQuestAcceptance: true,
  }],
  lessonSequenceIds: ['lesson-material-evidence'],
  systemIds: ['physics', 'presentation'],
};
