import {
  BROWSER_BALANCED_PROFILE,
  BROWSER_ENHANCED_PROFILE,
  QUEST_BASELINE_PROFILE,
  type AssetDefinition,
  type WorldBundle,
} from '../../../../packages/simulation-schema/src/index';

const LICENSE = 'XR School self-authored; redistribution permitted';
const sharedTexture = (
  id: string,
  family: 'painted' | 'metal',
  channel: 'base-color' | 'normal' | 'roughness',
): AssetDefinition => ({
  id,
  url: `/world-builder/circuit/${family}-${channel}.svg`,
  kind: 'texture',
  source: `XR School shared procedural ${family} PBR texture`,
  license: LICENSE,
  author: 'XR School',
  width: 512,
  height: 512,
  channels: [channel === 'base-color' ? 'baseColor' : channel],
  compression: 'SVG procedural',
});

const assets = [
  sharedTexture('states-painted-base', 'painted', 'base-color'),
  sharedTexture('states-painted-normal', 'painted', 'normal'),
  sharedTexture('states-painted-roughness', 'painted', 'roughness'),
  sharedTexture('states-metal-base', 'metal', 'base-color'),
  sharedTexture('states-metal-normal', 'metal', 'normal'),
  sharedTexture('states-metal-roughness', 'metal', 'roughness'),
  {
    id: 'states-environment',
    url: '/world-builder/circuit/workshop-environment.svg',
    kind: 'environment' as const,
    source: 'XR School shared procedural laboratory environment',
    license: LICENSE,
    author: 'XR School',
    width: 1024,
    height: 512,
    channels: ['baseColor'],
    compression: 'SVG procedural',
  },
];

export const STATES_WORLD: WorldBundle = {
  world: {
    id: 'states-of-matter-reference-world',
    version: '1.0.0',
    title: 'States of Matter Particle Lab',
    metersPerWorldUnit: 1,
    environmentId: 'matter-laboratory',
    qualityProfileIds: ['questBaseline', 'browserBalanced', 'browserEnhanced'],
    entityIds: ['floor', 'chamber', 'heater', 'particle-markers'],
    systemIds: ['particleMatter', 'boundedMotion', 'lesson', 'presentation'],
    scientificModelIds: ['matter-state-from-heat'],
    lessonSequenceId: 'matter-four-stage-lesson',
    assessmentSequenceId: 'matter-mastery',
    assetManifestId: 'matter-assets',
    acceptanceProfileId: 'matter-acceptance',
  },
  entities: [
    {
      id: 'floor',
      visualId: 'laboratory-floor',
      materialId: 'lab-floor',
      transform: { position: [0, 0, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
      interactionTags: ['environment'],
      accessibilityLabel: 'Particle laboratory floor',
    },
    {
      id: 'chamber',
      visualId: 'transparent-particle-chamber',
      materialId: 'chamber-shell',
      transform: { position: [0, 1.25, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
      interactionTags: ['container', 'observation'],
      accessibilityLabel: 'Transparent matter particle chamber',
    },
    {
      id: 'heater',
      visualId: 'heat-control-platform',
      materialId: 'heater',
      transform: { position: [0, 0.1, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
      interactionTags: ['heat-source'],
      accessibilityLabel: 'Illustrative heating platform',
    },
    {
      id: 'particle-markers',
      visualId: 'seeded-bounded-particle-cloud',
      materialId: 'particle-marker',
      transform: { position: [0, 0, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
      interactionTags: ['illustrative', 'particleMatter'],
      accessibilityLabel: 'Illustrative markers showing particle spacing and motion',
    },
  ],
  environments: [{
    id: 'matter-laboratory',
    background: { kind: 'color', value: '#08111f' },
    environmentMap: 'states-environment',
    fog: { color: '#08111f', near: 6, far: 18 },
    keyLight: {
      kind: 'directional',
      color: '#ffffff',
      intensity: 2,
      position: [4, 6, 4],
      target: [0, 1.2, 0],
      castsShadow: true,
    },
    fillLight: {
      kind: 'hemisphere',
      color: '#90cdf4',
      intensity: 1.2,
      position: [0, 5, 0],
    },
    accentLights: [],
    shadowCasters: ['heater', 'particle-markers'],
    exposure: 1,
    toneMapping: 'AgX',
  }],
  materials: [
    {
      id: 'lab-floor',
      model: 'standard',
      baseColor: '#111827',
      baseColorMap: 'states-painted-base',
      normalMap: 'states-painted-normal',
      normalScale: [0.28, 0.28],
      roughness: 0.86,
      roughnessMap: 'states-painted-roughness',
      metalness: 0,
      textureRepeat: [8, 8],
    },
    {
      id: 'heater',
      model: 'standard',
      baseColor: '#7c2d12',
      baseColorMap: 'states-metal-base',
      normalMap: 'states-metal-normal',
      normalScale: [0.2, 0.2],
      roughness: 0.36,
      roughnessMap: 'states-metal-roughness',
      metalness: 0.62,
      emissiveColor: '#ef4444',
      emissiveIntensity: 0.6,
      textureRepeat: [3, 3],
    },
    {
      id: 'particle-marker',
      model: 'standard',
      baseColor: '#60a5fa',
      baseColorMap: 'states-metal-base',
      normalMap: 'states-metal-normal',
      normalScale: [0.12, 0.12],
      roughness: 0.22,
      roughnessMap: 'states-metal-roughness',
      metalness: 0.28,
      emissiveColor: '#60a5fa',
      emissiveIntensity: 0.45,
    },
    {
      id: 'chamber-shell',
      model: 'standard',
      baseColor: '#38bdf8',
      roughness: 0.2,
      metalness: 0,
      opacity: 0.12,
      doubleSided: true,
    },
  ],
  qualityProfiles: [
    QUEST_BASELINE_PROFILE,
    BROWSER_BALANCED_PROFILE,
    BROWSER_ENHANCED_PROFILE,
  ],
  scientificModels: [{
    id: 'matter-state-from-heat',
    version: '1.0.0',
    domain: 'particleMatter',
    internalUnits: { heat: 'normalized teaching scale' },
    validInputRanges: { heat: { min: 0, max: 1, unit: 'normalized' } },
    assumptions: ['Heat is a normalized teaching control, not temperature'],
    limitations: ['Markers are illustrative and not literal molecule size, count, or trajectory'],
    referenceSources: ['NCERT Class 9 Science: Matter in Our Surroundings'],
    referenceVectors: [
      { id: 'solid', inputs: { heat: 0.18 }, expectedOutputs: { phase: 'solid', motionFactor: 0.18, spacingFactor: 0.12 } },
      { id: 'liquid', inputs: { heat: 0.48 }, expectedOutputs: { phase: 'liquid', motionFactor: 0.48, spacingFactor: 0.5 } },
      { id: 'gas', inputs: { heat: 0.82 }, expectedOutputs: { phase: 'gas', motionFactor: 0.82, spacingFactor: 1 } },
    ],
    numericalTolerance: 0.000000001,
  }],
  assessments: [{
    id: 'matter-mastery',
    objectiveId: 'objective-connect-spacing-motion-state',
    prompts: [
      {
        id: 'matter-observation',
        kind: 'observation',
        stageId: 'stage-liquid',
        question: 'What changes from solid to liquid?',
        options: [
          { id: 'slide', label: 'Particles remain close but can slide past each other' },
          { id: 'vanish', label: 'Particles vanish' },
        ],
        acceptedEvidenceIds: ['slide'],
        hint: 'Compare spacing and freedom of movement.',
        explanation: 'Liquid particles remain close while moving past one another.',
        retryPolicy: 'afterObservation',
      },
      {
        id: 'matter-misconception',
        kind: 'misconception',
        stageId: 'stage-gas',
        question: 'Does heating make the particles themselves grow?',
        options: [
          { id: 'grow', label: 'Yes, each particle gets much larger' },
          { id: 'move', label: 'No, they move faster and spread farther apart' },
        ],
        acceptedEvidenceIds: ['move'],
        hint: 'Watch motion and spacing, not marker size.',
        explanation: 'Heating changes particle energy and spacing, not particle size.',
        retryPolicy: 'immediateWithHint',
      },
      {
        id: 'matter-transfer',
        kind: 'transfer',
        stageId: 'stage-phase-change',
        question: 'What should cooling a gas eventually produce?',
        options: [
          { id: 'condense', label: 'A liquid, as particles slow and come closer' },
          { id: 'faster', label: 'An even faster gas' },
        ],
        acceptedEvidenceIds: ['condense'],
        hint: 'Reverse the heating sequence.',
        explanation: 'Removing heat can condense a gas into a liquid.',
        retryPolicy: 'immediateWithHint',
      },
    ],
    masteryRule: {
      requiredEvidenceCount: 3,
      requiredKinds: ['observation', 'misconception', 'transfer'],
      allowHintedMastery: true,
    },
  }],
  assetManifests: [{ id: 'matter-assets', assets }],
  acceptanceProfiles: [{
    id: 'matter-acceptance',
    requiredQualityProfileId: 'questBaseline',
    minSteadyFps: 72,
    maxDrawCalls: 120,
    maxVisibleTriangles: 250_000,
    requiresQuestAcceptance: true,
  }],
  lessonSequenceIds: ['matter-four-stage-lesson'],
  systemIds: ['particleMatter', 'boundedMotion', 'lesson', 'presentation'],
};
