import Fastify from 'fastify';
import cors from '@fastify/cors';

const app = Fastify({ logger: { level: 'info' } });

await app.register(cors, {
  origin: ['http://localhost:3000', /http:\/\/192\.168\.\d+\.\d+:3000/],
});

// Simulation catalog — seed data matching TypeSpec SimulationModule model
const SIMULATIONS = [
  {
    id: 'sim-up-you-go-snow-mountain-climbing-001',
    slug: 'up-you-go-snow-mountain-climbing',
    title: 'Snow Mountain Climbing',
    summary: 'Follow the NCERT group from its 2,134-metre camp toward the 2,700-metre snowfield through route reading, equipment checks, group movement, walking-stick technique, protected rope practice, slip recovery and a controlled return.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive snow route makes visibility, marker spacing, short-step balance, walking-stick placement, fixed-rope protection and group movement directly inspectable without exposing learners to real cold, altitude or fall hazards.',
    learningObjective: 'Students will sequence a supervised snow-mountain journey and explain how route assessment, suitable equipment, short balanced steps, protected rope practice, teamwork and a timely return support responsible participation.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 10,
    stages: 8,
    status: 'released',
  },
  {
    id: 'sim-up-you-go-camp-in-snow-001',
    slug: 'up-you-go-camp-in-snow',
    title: 'Camp in the Snow',
    summary: 'Build the NCERT snow camp through site selection, double-layer insulation, wind-resistant anchoring, drainage, supervised cooking, waste cleanup, feather sleeping bags and careful snowy walking.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive snow camp makes the tent layers, trapped-air insulation, guy-line tension, meltwater drainage and slippery morning conditions directly inspectable without exposing learners to real cold-weather hazards.',
    learningObjective: 'Students will sequence the textbook snow-camp routine and explain how insulation, anchoring, drainage, responsible cooking, waste removal, warm sleeping equipment and teamwork support a safe mountain camp.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 10,
    stages: 8,
    status: 'released',
  },
  {
    id: 'sim-up-you-go-rock-climbing-001',
    slug: 'up-you-go-rock-climbing',
    title: 'Rock Climbing',
    summary: 'Follow the NCERT Tekla rock-climbing episode through route observation, hold identification, safety checks, slip recovery, balanced climbing and controlled rappelling.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive training rock makes holds, body posture, rope tension and the protected climb-and-rappel sequence directly inspectable without exposing learners to a real fall hazard.',
    learningObjective: 'Students will sequence a supervised rock climb and explain how observation, fitted equipment, straight posture, secure holds, instructor-controlled rope and courage support safe participation.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 10,
    stages: 8,
    status: 'released',
  },
  {
    id: 'sim-up-you-go-river-crossing-adventure-001',
    slug: 'up-you-go-river-crossing-adventure',
    title: 'River Crossing Adventure',
    summary: 'Follow a supervised mountain-river adventure through equipment checks, piton anchors, sling attachment, careful footsteps, slip recovery and teamwork.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive mountain river lets learners inspect the protected crossing system at life scale, see the moving current and practise the textbook sequence without entering a real hazardous environment.',
    learningObjective: 'Students will explain how the main rope, piton anchors, safety sling, careful movement, trained supervision and teamwork support a protected river crossing.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 10,
    stages: 8,
    status: 'released',
  },
  {
    id: 'sim-treat-for-mosquitoes-mosquito-life-cycle-001',
    slug: 'treat-for-mosquitoes-mosquito-life-cycle',
    title: 'Life Cycle of the Mosquito',
    summary: 'Follow a malaria-carrying Anopheles mosquito through floating egg, aquatic larva, non-feeding pupa, adult emergence and the repeating reproductive cycle.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive wetland enlarges normally tiny aquatic life stages and lets learners inspect egg floats, larval posture, pupal metamorphosis and adult emergence around one connected habitat.',
    learningObjective: 'Students will sequence the four Anopheles mosquito life stages, distinguish aquatic from flying stages and identify safe ways to reduce breeding and bites.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 10,
    stages: 8,
    status: 'released',
  },
  {
    id: 'sim-treat-for-mosquitoes-malaria-diagnosis-001',
    slug: 'treat-for-mosquitoes-malaria-diagnosis',
    title: 'Diagnosis of Malaria',
    summary: 'Follow a medically safe malaria-diagnosis pathway from symptoms and exposure through professional sampling, thick and thin blood films, microscopy and rapid diagnostic testing.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'practicalLabSimulation',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive laboratory enlarges microscopic red blood cells and Plasmodium structures while letting learners perform a safe, non-invasive diagnostic sequence without handling real blood.',
    learningObjective: 'Students will explain why symptoms alone cannot confirm malaria and sequence the professional parasite-based tests used for diagnosis.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 10,
    stages: 8,
    status: 'released',
  },
  {
    id: 'sim-experiments-with-water-float-or-sink-001',
    slug: 'experiments-with-water-float-or-sink',
    title: 'What Floats, What Sinks?',
    summary: 'Predict and test six familiar objects in water, then connect each observation to material, shape, trapped air and average density.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'practicalLabSimulation',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive transparent tank makes surface motion, sinking paths and displaced-water effects visible while learners predict and test each object directly.',
    learningObjective: 'Students will classify tested objects as floating or sinking and explain that material, shape and trapped air affect the outcome.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 9,
    stages: 8,
    status: 'released',
  },
  {
    id: 'sim-experiments-with-water-dead-sea-salt-water-001',
    slug: 'experiments-with-water-dead-sea-salt-water',
    title: 'Dead Sea: Salt Water and Its Effects',
    summary: 'Compare eggs in fresh and concentrated salt water, reveal buoyant forces and explore the physical, ecological and safety effects of extreme salinity.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'practicalLabSimulation',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive dual-tank experiment makes dissolved salt, density changes, sinking paths and buoyant support visible at a scale learners can inspect directly.',
    learningObjective: 'Students will explain that dissolved salt increases water density and can increase buoyant support, while identifying important effects and safety precautions of extremely salty water.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 9,
    stages: 8,
    status: 'released',
  },
  {
    id: 'sim-experiments-with-water-soluble-insoluble-001',
    slug: 'experiments-with-water-soluble-insoluble',
    title: 'Soluble and Insoluble Substances',
    summary: 'Predict, stir and observe salt, sugar, sand, chalk powder and sawdust while distinguishing dissolving from suspension, settling and floating.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'practicalLabSimulation',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive beaker enlarges particle behaviour and makes dissolving, clouding, settling and floating directly comparable through repeatable learner-controlled tests.',
    learningObjective: 'Students will classify common substances as soluble or insoluble and distinguish a true solution from visible suspended, settled or floating particles.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 9,
    stages: 7,
    status: 'released',
  },
  {
    id: 'sim-every-drop-counts-rainwater-storage-001',
    slug: 'every-drop-counts-rainwater-storage',
    title: 'The Storage of Rainwater',
    summary: 'Build a rooftop rainwater-harvesting path through catchment, gutter, first flush, filter, covered tank and careful reuse.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive system makes the hidden path of roof runoff visible and lets learners trigger each cleaning and storage stage in sequence.',
    learningObjective: 'Students will sequence rooftop rainwater collection and explain why first-flush diversion, filtration and covered storage are important.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 9,
    stages: 7,
    status: 'released',
  },
  {
    id: 'sim-every-drop-counts-stepwell-structure-001',
    slug: 'every-drop-counts-stepwell-structure',
    title: 'A Stepwell Structure',
    summary: 'Explore how descending steps, landings, pillars, shaded galleries, a catchment and a deep reservoir work together.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive cutaway reveals the vertical relationship between stairways, changing water levels and the deep reservoir at a scale learners can inspect.',
    learningObjective: 'Students will identify the main parts of a stepwell and explain how its steps provide access when stored water levels change.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 9,
    stages: 7,
    status: 'released',
  },
  {
    id: 'sim-seeds-and-seeds-seed-dispersal-001',
    slug: 'seeds-and-seeds-seed-dispersal',
    title: 'Seed Dispersal',
    summary: 'Explore how seed adaptations support dispersal by wind, water, animals and explosive pods.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive habitat makes four different seed journeys visible at an inspectable scale and lets learners trigger each dispersal mechanism.',
    learningObjective: 'Students will compare dispersal by wind, water, animals and explosive pods and connect each method to observable seed adaptations.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 9,
    stages: 7,
    status: 'released',
  },
  {
    id: 'sim-mangoes-round-the-year-aam-papad-001',
    slug: 'mangoes-round-the-year-aam-papad',
    title: 'The Making of Aam Papad',
    summary: 'Prepare mamidi tandra by straining ripe mango pulp, mixing sugar and jaggery, and sun-drying repeated thin layers.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'practicalLabSimulation',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive workshop compresses a four-week traditional preservation process into a visible sequence where learners prepare, layer and dry mango pulp.',
    learningObjective: 'Students will sequence the traditional making of aam papad and explain how sun-drying and reduced moisture preserve mango beyond its season.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 8,
    stages: 7,
    status: 'released',
  },
  {
    id: 'sim-mangoes-round-the-year-milk-spoilage-001',
    slug: 'mangoes-round-the-year-milk-spoilage',
    title: 'Milk Spoilage',
    summary: 'Compare milk stored under three conditions and observe souring, curd formation, separation and gas over 24 simulated hours.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'interactive3d',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive time-lapse makes gradual milk spoilage visible and lets learners compare controlled storage conditions side by side without tasting unsafe samples.',
    learningObjective: 'Students will identify signs of milk spoilage and explain how boiling, covering and refrigeration can slow microbial growth.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 8,
    stages: 6,
    status: 'released',
  },
  {
    id: 'sim-seeds-and-seeds-pitcher-plant-001',
    slug: 'seeds-and-seeds-pitcher-plant',
    title: 'Pitcher Plant — The Insect Hunter',
    summary: 'Follow an insect into a pitcher leaf and observe attraction, trapping, digestion and mineral absorption.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive cutaway makes the hidden trapping and nutrient-absorption sequence visible at a scale learners can inspect from every angle.',
    learningObjective: 'Students will sequence how a pitcher plant traps insects and explain that insects supply minerals while photosynthesis supplies sugars.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 8,
    stages: 7,
    status: 'released',
  },
  {
    id: 'sim-mangoes-round-the-year-food-spoilage-001',
    slug: 'mangoes-round-the-year-food-spoilage',
    title: 'Mangoes Round the Year: Food Spoilage',
    summary: 'Compare mango pieces stored in four conditions and identify visible signs of spoilage over five simulated days.',
    gradeBands: ['class3To5'],
    subjects: ['environmentalScience'],
    applicableBoards: ['cbse'],
    simulationFormat: 'interactive3d',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive time-lapse comparison makes slow spoilage changes visible and lets learners inspect four controlled storage conditions side by side.',
    learningObjective: 'Students will identify common signs of food spoilage and explain how cooling, covering and salt can slow spoilage.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 8,
    stages: 6,
    status: 'released',
  },
  {
    id: 'sim-sorting-materials-by-shape-001',
    slug: 'sorting-materials-by-shape',
    title: 'Sorting Materials According to Their Shape',
    summary: 'Observe familiar objects and sort them into sphere, cylinder, cuboid and cone groups using visible shape properties.',
    gradeBands: ['class6To8'],
    subjects: ['science'],
    applicableBoards: ['cbse'],
    simulationFormat: 'interactive3d',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive sorting table lets learners inspect, compare and physically classify three-dimensional objects while receiving immediate corrective feedback.',
    learningObjective: 'Students will classify familiar objects by overall shape and explain the observable features of spheres, cylinders, cuboids and cones.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 8,
    stages: 8,
    status: 'released',
  },
  {
    id: 'sim-fibre-to-fabric-cotton-ginning-001',
    slug: 'fibre-to-fabric-cotton-ginning',
    title: 'The Process of Cotton Ginning',
    summary: 'Operate a cotton gin to separate picked cotton into clean fibres and cotton seeds, then prepare the fibres for spinning.',
    gradeBands: ['class6To8'],
    subjects: ['science'],
    applicableBoards: ['cbse'],
    simulationFormat: 'practicalLabSimulation',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The interactive workshop makes the hidden roller-separation mechanism visible and lets learners compare picked cotton with the clean fibre and seed outputs.',
    learningObjective: 'Students will operate a simplified cotton gin and explain that ginning separates cotton fibres from cotton seeds before spinning.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 8,
    stages: 6,
    status: 'released',
  },
  {
    id: 'sim-fibre-to-fabric-cotton-farming-001',
    slug: 'fibre-to-fabric-cotton-farming',
    title: 'Cotton Farming',
    summary: 'Prepare black soil, sow cotton seeds, support plant growth, observe cotton bolls and harvest mature cotton fibre.',
    gradeBands: ['class6To8'],
    subjects: ['science'],
    applicableBoards: ['cbse'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive farm compresses a months-long plant-growth process into a spatial sequence where learners perform each field task and observe cotton bolls developing.',
    learningObjective: 'Students will sequence the major stages of cotton farming from soil preparation and sowing through boll formation, maturation and harvesting.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 9,
    stages: 7,
    status: 'released',
  },
  {
    id: 'sim-components-of-food-mineral-sources-001',
    slug: 'components-of-food-mineral-sources',
    title: 'The Sources of Minerals in Food',
    summary: 'Match calcium, iodine and iron to representative food sources and identify the important body function supported by each mineral.',
    gradeBands: ['class6To8'],
    subjects: ['science'],
    applicableBoards: ['cbse'],
    simulationFormat: 'interactive3d',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive mineral discovery lab turns a comparison chart into a spatial matching task with immediate feedback and visible three-mineral progress.',
    learningObjective: 'Students will match calcium, iodine and iron to representative food sources and explain one important body function of each mineral.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 8,
    stages: 6,
    status: 'released',
  },
  {
    id: 'sim-components-of-food-vitamins-deficiencies-001',
    slug: 'components-of-food-vitamins-deficiencies',
    title: 'Sources of Vitamins and Their Deficiencies',
    summary: 'Match vitamins A, B1, C and D to representative food or natural sources and identify the characteristic condition caused by a long-term deficiency.',
    gradeBands: ['class6To8'],
    subjects: ['science'],
    applicableBoards: ['cbse'],
    simulationFormat: 'interactive3d',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The immersive nutrition lab turns a dense comparison table into a spatial matching task with immediate body-system feedback, repeatable practice, and a visible four-vitamin progress model.',
    learningObjective: 'Students will match vitamins A, B1, C and D to representative sources and explain the deficiency condition linked to a long-term lack of each vitamin.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 9,
    stages: 6,
    status: 'released',
  },
  {
    id: 'sim-components-of-food-lipid-test-001',
    slug: 'components-of-food-lipid-test',
    title: 'Test the Presence of Lipids',
    summary: 'Crush food samples on white paper, let the paper dry, and inspect it against light to identify the persistent translucent patch produced by lipids.',
    gradeBands: ['class6To8'],
    subjects: ['science'],
    applicableBoards: ['cbse'],
    simulationFormat: 'practicalLabSimulation',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'The simulation makes an easily missed translucent-paper observation large, repeatable, and comparable across several food samples. Guided VR staging lets every learner perform the complete investigation without wasting food or tearing the paper before observing the result.',
    learningObjective: 'Students will perform the translucent-spot test and use observations to identify whether a food sample contains lipids.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 8,
    stages: 7,
    status: 'released',
  },
  {
    id: 'sim-pollination-001',
    slug: 'pollination',
    title: 'Plant Pollination & Growth Cycle',
    summary: 'Walk through a flowering garden. Watch pollen transfer, seed formation, germination, and a full plant life cycle unfold in immersive VR.',
    gradeBands: ['class6To8', 'class9To10'],
    subjects: ['biology', 'environmentalScience'],
    applicableBoards: ['cbse', 'icse'],
    simulationFormat: 'immersiveVr',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'Pollination occurs at microscopic scale and involves invisible pollen transfer that students cannot witness directly. VR makes the entire process—from pollen grain to seed formation—navigable and spatial in a way no diagram, video, or physical classroom can replicate.',
    learningObjective: 'Students will be able to sequence the 8 stages of plant reproduction from pollen production through germination.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 10,
    stages: 8,
    status: 'released',
  },
  {
    id: 'sim-circuit-001',
    slug: 'circuit',
    title: 'Electric Circuits & Resistance (Ohm\'s Law)',
    summary: 'Toggle a switch, swap resistors, and watch electrons flow in real time. Discover V=IR through direct interaction with a 3D circuit.',
    gradeBands: ['class8To10', 'class9To10'],
    subjects: ['physics'],
    applicableBoards: ['cbse', 'icse'],
    simulationFormat: 'interactive3d',
    xrFitType: 'strongVrFit',
    xrFitJustification: 'Electric current is invisible. Visualising electron flow as glowing particles gives students a spatial, intuitive understanding of current direction and magnitude that no static diagram can provide. The real-time feedback between resistance, current, and bulb brightness makes Ohm\'s Law immediate and tactile.',
    learningObjective: 'Students will apply Ohm\'s Law (V=IR) to predict how changing resistance affects current and explain observations in a series circuit.',
    evidenceConfidenceLevel: 'expertDesigned',
    comfortRiskLevel: 'low',
    expectedDurationMinutes: 8,
    stages: 4,
    status: 'released',
  },
];

app.get('/v1/simulation-modules', async () => ({
  items: SIMULATIONS,
  page: { page: 1, pageSize: 20, totalItems: SIMULATIONS.length, totalPages: 1 },
}));

app.get<{ Params: { moduleId: string } }>('/v1/simulation-modules/:moduleId', async (req, reply) => {
  const sim = SIMULATIONS.find(s => s.id === req.params.moduleId || s.slug === req.params.moduleId);
  if (!sim) { reply.code(404); return { code: 'NOT_FOUND', message: 'Simulation not found' }; }
  return sim;
});

app.get('/health', async () => ({ status: 'ok', service: 'xr-school-api', version: '0.1.0' }));

const host = '0.0.0.0';
const port = 3001;
await app.listen({ port, host });
console.log(`\n  ✓ API running at http://localhost:${port}`);
console.log(`  ✓ Simulations: http://localhost:${port}/v1/simulation-modules\n`);
