import Link from 'next/link';

const SIMS = [
  {
    slug: 'sunita-in-space-space-shuttle-launch',
    emoji: '🚀',
    color: '#fb923c',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'A Space Shuttle Launch',
    xrFit: 'Strong VR Fit',
    stages: 10,
    minutes: 12,
  },
  {
    slug: 'walls-tell-stories-ancient-fort-visit',
    emoji: '🏰',
    color: '#f5c16c',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'A Visit to an Ancient Fort',
    xrFit: 'Strong VR Fit',
    stages: 8,
    minutes: 10,
  },
  {
    slug: 'up-you-go-snow-mountain-climbing',
    emoji: '🏔️',
    color: '#a7f3d0',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'Snow Mountain Climbing',
    xrFit: 'Strong VR Fit',
    stages: 8,
    minutes: 10,
  },
  {
    slug: 'up-you-go-camp-in-snow',
    emoji: '🏕️',
    color: '#7dd3fc',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'Camp in the Snow',
    xrFit: 'Strong VR Fit',
    stages: 8,
    minutes: 10,
  },
  {
    slug: 'up-you-go-rock-climbing',
    emoji: '🧗🏽‍♀️',
    color: '#fbbf24',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'Rock Climbing',
    xrFit: 'Strong VR Fit',
    stages: 8,
    minutes: 10,
  },
  {
    slug: 'up-you-go-river-crossing-adventure',
    emoji: '🪢',
    color: '#7dd3fc',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'River Crossing Adventure',
    xrFit: 'Strong VR Fit',
    stages: 8,
    minutes: 10,
  },
  {
    slug: 'treat-for-mosquitoes-mosquito-life-cycle',
    emoji: '🦟',
    color: '#67e8f9',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'Life Cycle of the Mosquito',
    xrFit: 'Strong VR Fit',
    stages: 8,
    minutes: 10,
  },
  {
    slug: 'treat-for-mosquitoes-malaria-diagnosis',
    emoji: '🔬',
    color: '#38bdf8',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'Diagnosis of Malaria',
    xrFit: 'Strong VR Fit',
    stages: 8,
    minutes: 10,
  },
  {
    slug: 'experiments-with-water-float-or-sink',
    emoji: '💧',
    color: '#38bdf8',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'What Floats, What Sinks?',
    xrFit: 'Strong VR Fit',
    stages: 8,
    minutes: 9,
  },
  {
    slug: 'experiments-with-water-dead-sea-salt-water',
    emoji: '🧂',
    color: '#67e8f9',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'Dead Sea: Salt Water and Its Effects',
    xrFit: 'Strong VR Fit',
    stages: 8,
    minutes: 9,
  },
  {
    slug: 'experiments-with-water-soluble-insoluble',
    emoji: '🥄',
    color: '#5eead4',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'Soluble and Insoluble Substances',
    xrFit: 'Strong VR Fit',
    stages: 7,
    minutes: 9,
  },
  {
    slug: 'every-drop-counts-rainwater-storage',
    emoji: '🌧️',
    color: '#67e8f9',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'The Storage of Rainwater',
    xrFit: 'Strong VR Fit',
    stages: 7,
    minutes: 9,
  },
  {
    slug: 'every-drop-counts-stepwell-structure',
    emoji: '🏛️',
    color: '#f5c16c',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'A Stepwell Structure',
    xrFit: 'Strong VR Fit',
    stages: 7,
    minutes: 9,
  },
  {
    slug: 'seeds-and-seeds-seed-dispersal',
    emoji: '🌬️',
    color: '#86efac',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'Seed Dispersal',
    xrFit: 'Strong VR Fit',
    stages: 7,
    minutes: 9,
  },
  {
    slug: 'mangoes-round-the-year-aam-papad',
    emoji: '🥭',
    color: '#facc15',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'The Making of Aam Papad',
    xrFit: 'Strong VR Fit',
    stages: 7,
    minutes: 8,
  },
  {
    slug: 'mangoes-round-the-year-milk-spoilage',
    emoji: '🥛',
    color: '#7dd3fc',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'Milk Spoilage',
    xrFit: 'Strong VR Fit',
    stages: 6,
    minutes: 8,
  },
  {
    slug: 'seeds-and-seeds-pitcher-plant',
    emoji: '🌿',
    color: '#a3e635',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'Pitcher Plant — The Insect Hunter',
    xrFit: 'Strong VR Fit',
    stages: 7,
    minutes: 8,
  },
  {
    slug: 'mangoes-round-the-year-food-spoilage',
    emoji: '🥭',
    color: '#fb923c',
    subject: 'Environmental Studies',
    grade: 'Class 5',
    title: 'Mangoes Round the Year: Food Spoilage',
    xrFit: 'Strong VR Fit',
    stages: 6,
    minutes: 8,
  },
  {
    slug: 'sorting-materials-by-shape',
    emoji: '⚽',
    color: '#4ade80',
    subject: 'Science',
    grade: 'Class 6',
    title: 'Sorting Materials According to Their Shape',
    xrFit: 'Strong VR Fit',
    stages: 8,
    minutes: 8,
  },
  {
    slug: 'fibre-to-fabric-cotton-ginning',
    emoji: '⚙️',
    color: '#fbbf24',
    subject: 'Science',
    grade: 'Class 6',
    title: 'The Process of Cotton Ginning',
    xrFit: 'Strong VR Fit',
    stages: 6,
    minutes: 8,
  },
  {
    slug: 'fibre-to-fabric-cotton-farming',
    emoji: '☁️',
    color: '#86efac',
    subject: 'Science',
    grade: 'Class 6',
    title: 'Cotton Farming',
    xrFit: 'Strong VR Fit',
    stages: 7,
    minutes: 9,
  },
  {
    slug: 'components-of-food-mineral-sources',
    emoji: '🧂',
    color: '#60a5fa',
    subject: 'Science',
    grade: 'Class 6',
    title: 'The Sources of Minerals in Food',
    xrFit: 'Strong VR Fit',
    stages: 6,
    minutes: 8,
  },
  {
    slug: 'components-of-food-vitamins-deficiencies',
    emoji: '🥕',
    color: '#4ade80',
    subject: 'Science',
    grade: 'Class 6',
    title: 'Sources of Vitamins and Their Deficiencies',
    xrFit: 'Strong VR Fit',
    stages: 6,
    minutes: 9,
  },
  {
    slug: 'components-of-food-lipid-test',
    emoji: '🥜',
    color: '#22d3ee',
    subject: 'Science',
    grade: 'Class 6',
    title: 'Test the Presence of Lipids',
    xrFit: 'Strong VR Fit',
    stages: 7,
    minutes: 8,
  },
  {
    slug: 'pollination',
    emoji: '🌸',
    color: '#34d399',
    subject: 'Biology',
    grade: 'Class 6–10',
    title: 'Plant Pollination & Growth Cycle',
    xrFit: 'Strong VR Fit',
    stages: 8,
    minutes: 10,
  },
  {
    slug: 'nutrition-in-plants-secret-kitchen',
    emoji: '🌿',
    color: '#84cc16',
    subject: 'Science',
    grade: 'Class 7',
    title: 'The Secret Kitchen of the Garden',
    xrFit: 'Strong VR Fit',
    stages: 11,
    minutes: 12,
  },
  {
    slug: 'circuit',
    emoji: '⚡',
    color: '#fbbf24',
    subject: 'Physics',
    grade: 'Class 8–10',
    title: 'Electric Circuits & Resistance',
    xrFit: 'Strong VR Fit',
    stages: 4,
    minutes: 8,
  },
];

export default function SimulationsPage() {
  return (
    <main style={{ minHeight: '100vh', padding: '2rem', background: '#0a0f1a' }}>
      <div style={{ maxWidth: 900, margin: '0 auto' }}>
        <Link href="/" style={{ color: '#6b7280', fontSize: '0.875rem', display: 'inline-block', marginBottom: 32 }}>← Back</Link>
        <h1 style={{ fontSize: '2rem', fontWeight: 800, marginBottom: 8 }}>Simulation Catalog</h1>
        <p style={{ color: '#6b7280', marginBottom: 40 }}>{SIMS.length} simulations · MVP release</p>

        <div style={{ display: 'grid', gap: 16 }}>
          {SIMS.map(s => (
            <Link key={s.slug} href={`/simulations/${s.slug}`} style={{ display: 'flex', alignItems: 'center', gap: 20, padding: '20px 24px', borderRadius: 12, background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', textDecoration: 'none' }}>
              <span style={{ fontSize: 40, flexShrink: 0 }}>{s.emoji}</span>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.08em', color: s.color, marginBottom: 4 }}>{s.subject} · {s.grade}</div>
                <div style={{ fontWeight: 700, color: '#f3f4f6', fontSize: '1.05rem' }}>{s.title}</div>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 6, flexShrink: 0 }}>
                <span style={{ padding: '3px 10px', borderRadius: 99, fontSize: 11, background: 'rgba(79,142,247,0.15)', color: '#4f8ef7', fontWeight: 600 }}>Launch →</span>
                <span style={{ fontSize: 11, color: '#6b7280' }}>{s.stages} stages · {s.minutes} min</span>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </main>
  );
}
