import type {
  CourseRecord,
  CurriculumChapterRecord,
  GradeBand,
  LearningConceptRecord,
  SimulationModuleRecord,
} from '@xr-school/simulation-schema';
import {
  GUIDED_CLASS5_CHAPTER_IDS,
  GUIDED_CLASS5_CONCEPT_IDS,
  GUIDED_CLASS5_SIMULATION_IDS,
  GUIDED_CLASS6_CHAPTER_IDS,
  GUIDED_CLASS6_CONCEPT_IDS,
  GUIDED_CLASS6_SIMULATION_IDS,
  GUIDED_CLASS7_CHAPTER_IDS,
  GUIDED_CLASS7_CONCEPT_IDS,
  GUIDED_CLASS7_SIMULATION_IDS,
  GUIDED_CURRICULUM_CHAPTERS,
  GUIDED_LEARNING_CONCEPTS,
} from './implemented/guided/curriculum.js';
import {
  INTERACTIVE_CLASS6_CHAPTER_IDS,
  INTERACTIVE_CLASS6_CONCEPT_IDS,
  INTERACTIVE_CLASS6_SIMULATION_IDS,
  INTERACTIVE_CURRICULUM_CHAPTERS,
  INTERACTIVE_LEARNING_CONCEPTS,
} from './implemented/interactive/curriculum.js';

export const LEARNING_CONCEPTS: LearningConceptRecord[] = [
  {
    id: 'concept-flower-structure',
    canonicalName: 'Flower structure',
    aliases: ['parts of a flower', 'stamen and stigma'],
    subject: 'biology',
    description: 'The reproductive structures of a flower and the role each part plays.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-pollination', 'concept-fertilisation'],
    commonMisconceptions: ['All visible flower parts have the same reproductive role.'],
    practicalRelevance: 'Supports observation of flowering crops and plant reproduction.',
    searchKeywords: ['anther', 'stigma', 'ovary', 'petal'],
  },
  {
    id: 'concept-pollination',
    canonicalName: 'Pollination',
    aliases: ['pollen transfer', 'cross-pollination'],
    subject: 'biology',
    description: 'Transfer of pollen from an anther to a compatible stigma.',
    prerequisiteConceptIds: ['concept-flower-structure'],
    relatedConceptIds: ['concept-fertilisation', 'concept-seed-germination'],
    commonMisconceptions: ['Pollination and fertilisation are the same event.'],
    practicalRelevance: 'Explains pollinator value in gardens, orchards, and food production.',
    searchKeywords: ['bee', 'pollinator', 'pollen', 'stigma'],
  },
  {
    id: 'concept-fertilisation',
    canonicalName: 'Fertilisation',
    aliases: ['plant fertilization', 'fusion of gametes'],
    subject: 'biology',
    description: 'Fusion of reproductive cells after successful pollination, leading toward seed formation.',
    prerequisiteConceptIds: ['concept-pollination'],
    relatedConceptIds: ['concept-flower-structure', 'concept-seed-germination'],
    commonMisconceptions: ['A seed forms immediately when pollen touches a flower.'],
    practicalRelevance: 'Connects flower biology to fruit and seed production.',
    searchKeywords: ['ovule', 'ovary', 'seed formation'],
  },
  {
    id: 'concept-seed-germination',
    canonicalName: 'Seed germination',
    aliases: ['germination', 'seed sprouting'],
    subject: 'biology',
    description: 'Growth of a seed into a seedling when water, oxygen, and temperature are suitable.',
    prerequisiteConceptIds: ['concept-fertilisation'],
    relatedConceptIds: ['concept-pollination'],
    commonMisconceptions: ['Seeds germinate without suitable environmental conditions.'],
    practicalRelevance: 'Informs crop sowing, kitchen gardens, and seed care.',
    searchKeywords: ['seedling', 'sprout', 'plant growth'],
  },
  {
    id: 'concept-electric-current',
    canonicalName: 'Electric current',
    aliases: ['current', 'flow of charge'],
    subject: 'physics',
    description: 'The rate of electric charge flow through a conducting path.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-closed-circuit', 'concept-resistance', 'concept-ohms-law'],
    commonMisconceptions: ['Current is consumed by a bulb.'],
    practicalRelevance: 'Supports safe reasoning about appliances, batteries, and circuits.',
    searchKeywords: ['charge', 'ampere', 'electron flow'],
  },
  {
    id: 'concept-closed-circuit',
    canonicalName: 'Closed circuit',
    aliases: ['complete circuit', 'circuit path'],
    subject: 'physics',
    description: 'An unbroken conducting path that allows electric current to flow.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-electric-current', 'concept-resistance'],
    commonMisconceptions: ['A switch creates current rather than completing a path.'],
    practicalRelevance: 'Explains switches, torch circuits, and basic fault finding.',
    searchKeywords: ['switch', 'battery', 'bulb', 'wire'],
  },
  {
    id: 'concept-resistance',
    canonicalName: 'Electrical resistance',
    aliases: ['resistance', 'resistor'],
    subject: 'physics',
    description: 'Opposition to charge flow, measured in ohms.',
    prerequisiteConceptIds: ['concept-electric-current'],
    relatedConceptIds: ['concept-ohms-law', 'concept-closed-circuit'],
    commonMisconceptions: ['Higher resistance makes current move faster.'],
    practicalRelevance: 'Helps select components and understand heating and brightness.',
    searchKeywords: ['ohm', 'resistor value', 'brightness'],
  },
  {
    id: 'concept-ohms-law',
    canonicalName: "Ohm's law",
    aliases: ['V equals IR', 'voltage current resistance'],
    subject: 'physics',
    description: 'The quantitative relationship between voltage, current, and resistance.',
    prerequisiteConceptIds: ['concept-electric-current', 'concept-resistance'],
    relatedConceptIds: ['concept-closed-circuit'],
    commonMisconceptions: ['Voltage and current are interchangeable quantities.'],
    practicalRelevance: 'Enables prediction of current in simple electrical systems.',
    searchKeywords: ['V=IR', 'voltage', 'current calculation'],
  },
  {
    id: 'concept-states-of-matter',
    canonicalName: 'States of matter',
    aliases: ['solid liquid gas', 'phases of matter'],
    subject: 'chemistry',
    description: 'Observable forms of matter produced by different particle arrangements and energies.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-particle-motion', 'concept-phase-change'],
    commonMisconceptions: ['Particles exist only in gases.'],
    practicalRelevance: 'Explains everyday materials, weather, cooking, and storage.',
    searchKeywords: ['solid', 'liquid', 'gas', 'matter'],
  },
  {
    id: 'concept-particle-motion',
    canonicalName: 'Particle motion',
    aliases: ['kinetic particle theory', 'particle movement'],
    subject: 'physics',
    description: 'Microscopic particle speed, spacing, and movement in different states of matter.',
    prerequisiteConceptIds: ['concept-states-of-matter'],
    relatedConceptIds: ['concept-phase-change'],
    commonMisconceptions: ['Particles in solids do not move.'],
    practicalRelevance: 'Builds a mental model for diffusion, heating, and cooling.',
    searchKeywords: ['kinetic energy', 'spacing', 'vibration'],
  },
  {
    id: 'concept-phase-change',
    canonicalName: 'Phase change',
    aliases: ['change of state', 'melting boiling condensation'],
    subject: 'chemistry',
    description: 'A reversible change between states caused by energy transfer.',
    prerequisiteConceptIds: ['concept-states-of-matter', 'concept-particle-motion'],
    relatedConceptIds: [],
    commonMisconceptions: ['Heating creates new particles.'],
    practicalRelevance: 'Explains refrigeration, rainfall, evaporation, and cooking.',
    searchKeywords: ['melting', 'boiling', 'freezing', 'condensation'],
  },
  {
    id: 'concept-food-sources',
    canonicalName: 'Sources of food',
    aliases: ['food origins', 'where food comes from'],
    subject: 'science',
    description: 'Classification of food ingredients by the living source from which they are obtained.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-plant-products', 'concept-animal-products', 'concept-edible-fungi'],
    commonMisconceptions: ['Food source categories are the same as food groups.'],
    practicalRelevance: 'Connects meals and markets to farms, animals, and fungi.',
    searchKeywords: ['ingredients', 'origin', 'meal'],
  },
  {
    id: 'concept-plant-products',
    canonicalName: 'Plant food products',
    aliases: ['plant sources', 'foods from plants'],
    subject: 'biology',
    description: 'Foods obtained from plant parts including seeds, fruits, leaves, roots, and stems.',
    prerequisiteConceptIds: ['concept-food-sources'],
    relatedConceptIds: ['concept-animal-products', 'concept-edible-fungi'],
    commonMisconceptions: ['Only green vegetables are plant products.'],
    practicalRelevance: 'Supports nutrition, farming, and ingredient-label discussions.',
    searchKeywords: ['grain', 'pulse', 'fruit', 'vegetable'],
  },
  {
    id: 'concept-animal-products',
    canonicalName: 'Animal food products',
    aliases: ['animal sources', 'foods from animals'],
    subject: 'biology',
    description: 'Foods obtained from animals, including milk, eggs, honey, meat, and fish.',
    prerequisiteConceptIds: ['concept-food-sources'],
    relatedConceptIds: ['concept-plant-products', 'concept-edible-fungi'],
    commonMisconceptions: ['Milk and honey are plant products.'],
    practicalRelevance: 'Links food choices to dairy, poultry, beekeeping, and fisheries.',
    searchKeywords: ['milk', 'egg', 'honey', 'fish'],
  },
  {
    id: 'concept-edible-fungi',
    canonicalName: 'Edible fungi',
    aliases: ['mushrooms', 'fungal food sources'],
    subject: 'biology',
    description: 'Fungi used as food and their distinction from plants and animals.',
    prerequisiteConceptIds: ['concept-food-sources'],
    relatedConceptIds: ['concept-plant-products', 'concept-animal-products'],
    commonMisconceptions: ['Mushrooms are plants.'],
    practicalRelevance: 'Supports accurate food classification and safe food-source discussion.',
    searchKeywords: ['fungus', 'mushroom', 'decomposer'],
  },
  {
    id: 'concept-fungi',
    canonicalName: 'Fungi as a distinct kingdom',
    aliases: ['fungal organisms', 'fungus'],
    subject: 'biology',
    description: 'Fungi are organisms that absorb nutrients from their surroundings rather than making food by photosynthesis.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-mycelium', 'concept-decomposition', 'concept-edible-fungi'],
    commonMisconceptions: ['Fungi are green plants that make their own food.'],
    practicalRelevance: 'Supports recognition of mushrooms and moulds and safe reasoning about useful and harmful fungi.',
    searchKeywords: ['fungi', 'mushroom', 'mould', 'spore', 'absorbs nutrients'],
  },
  {
    id: 'concept-irrigation',
    canonicalName: 'Irrigation and crop water needs',
    aliases: ['supplying water to crops', 'crop irrigation'],
    subject: 'science',
    description: 'Irrigation is the planned artificial supply of water to crops at suitable intervals when soil moisture or rainfall is insufficient.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-irrigation-water-sources', 'concept-irrigation-method-selection'],
    commonMisconceptions: ['Irrigation means removing weeds or harvesting crops.'],
    practicalRelevance: 'Supports crop establishment, nutrient transport, photosynthesis and protection during dry conditions.',
    searchKeywords: ['irrigation', 'crop water', 'roots', 'soil moisture', 'germination'],
  },
  {
    id: 'concept-irrigation-water-sources',
    canonicalName: 'Sources of irrigation water',
    aliases: ['farm water sources', 'wells ponds rivers dams canals'],
    subject: 'science',
    description: 'Irrigation water may be obtained from groundwater, collected surface water, rivers, reservoirs and canal networks.',
    prerequisiteConceptIds: ['concept-irrigation'],
    relatedConceptIds: ['concept-irrigation-method-selection'],
    commonMisconceptions: ['All farms obtain irrigation water from the same type of source.'],
    practicalRelevance: 'Connects local rainfall, groundwater, storage and water distribution with agricultural decisions.',
    searchKeywords: ['well', 'tube well', 'pond', 'river', 'dam', 'canal', 'groundwater'],
  },
  {
    id: 'concept-irrigation-method-selection',
    canonicalName: 'Selecting an irrigation method',
    aliases: ['traditional sprinkler drip irrigation', 'water-efficient irrigation'],
    subject: 'science',
    description: 'Traditional lifting devices, sprinkler systems and drip systems deliver water differently and suit different terrain, crops, budgets and water availability.',
    prerequisiteConceptIds: ['concept-irrigation', 'concept-irrigation-water-sources'],
    relatedConceptIds: [],
    commonMisconceptions: ['The same irrigation method is best for every field and crop.'],
    practicalRelevance: 'Supports water conservation and evidence-based choices for farms, orchards, gardens and uneven land.',
    searchKeywords: ['moat', 'dhekli', 'chain pump', 'rahat', 'sprinkler', 'drip', 'water conservation'],
  },
  {
    id: 'concept-crop-harvest-maturity',
    canonicalName: 'Cereal crop maturity and harvesting',
    aliases: ['harvest-ready crop', 'mature cereal crop', 'harvesting methods'],
    subject: 'science',
    description: 'Harvesting is cutting and gathering a mature crop; harvest-ready cereals are commonly golden-yellow and dry with full, firm grain, and may be cut with a sickle or harvesting machine.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-threshing-and-winnowing', 'concept-grain-drying-and-storage'],
    commonMisconceptions: ['A green cereal crop with soft, developing grain is ready for harvesting.'],
    practicalRelevance: 'Supports correct harvest timing and recognition of manual and mechanical harvesting methods that reduce avoidable crop loss.',
    searchKeywords: ['harvesting', 'mature crop', 'golden cereal', 'firm grain', 'sickle', 'harvester'],
  },
  {
    id: 'concept-threshing-and-winnowing',
    canonicalName: 'Threshing and winnowing grain',
    aliases: ['grain separation', 'separating grain from stalk and chaff', 'combine harvester'],
    subject: 'science',
    description: 'Threshing detaches grain from harvested stalks, while winnowing uses moving air to carry lighter chaff away from heavier grain.',
    prerequisiteConceptIds: ['concept-crop-harvest-maturity'],
    relatedConceptIds: ['concept-grain-drying-and-storage'],
    commonMisconceptions: ['Threshing and winnowing are two names for the same separation process.'],
    practicalRelevance: 'Explains how a thresher, combine harvester and controlled airflow prepare harvested grain for drying and storage.',
    searchKeywords: ['threshing', 'thresher', 'winnowing', 'chaff', 'stalk', 'combine harvester', 'airflow'],
  },
  {
    id: 'concept-grain-drying-and-storage',
    canonicalName: 'Drying and safe storage of grain',
    aliases: ['crop storage', 'protecting stored grain', 'post-harvest grain care'],
    subject: 'science',
    description: 'Clean grain is dried to lower moisture, then stored in clean, dry, inspected bags, bins, granaries, warehouses or silos that limit moisture and pest damage.',
    prerequisiteConceptIds: ['concept-threshing-and-winnowing'],
    relatedConceptIds: ['concept-crop-harvest-maturity'],
    commonMisconceptions: ['Damp grain is safe in open bags, or drying alone permanently prevents all storage damage.'],
    practicalRelevance: 'Supports prevention of grain loss caused by excess moisture, fungi, other microorganisms, insects, rodents and birds.',
    searchKeywords: ['grain drying', 'grain storage', 'moisture', 'fungi', 'insects', 'rodents', 'granary', 'silo'],
  },
  {
    id: 'concept-virus-structure',
    canonicalName: 'Virus structure',
    aliases: ['parts of a virus', 'viral genetic material and protein coat'],
    subject: 'biology',
    description: 'A virus contains genetic material protected by a protein coat; some viruses also have an envelope and attachment structures.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-virus-replication', 'concept-virus-transmission-prevention'],
    commonMisconceptions: ['A virus is a complete living cell that can reproduce independently.'],
    practicalRelevance: 'Explains why viruses require suitable living host cells and why their surface structures affect which cells they can enter.',
    searchKeywords: ['virus', 'genetic material', 'protein coat', 'envelope', 'host cell'],
  },
  {
    id: 'concept-virus-replication',
    canonicalName: 'Viral replication in a host cell',
    aliases: ['virus life cycle', 'attachment entry copying assembly release'],
    subject: 'biology',
    description: 'Viruses attach to suitable cells, enter or release genetic material, use host machinery to copy parts, assemble particles and release them.',
    prerequisiteConceptIds: ['concept-virus-structure'],
    relatedConceptIds: ['concept-virus-transmission-prevention'],
    commonMisconceptions: ['Viruses grow and divide independently like ordinary cells.'],
    practicalRelevance: 'Builds a scientific explanation for infection and for why antibiotics do not cure viral infections.',
    searchKeywords: ['attachment', 'entry', 'copying', 'assembly', 'release', 'host'],
  },
  {
    id: 'concept-virus-transmission-prevention',
    canonicalName: 'Viral transmission and prevention',
    aliases: ['viral spread', 'break the chain of infection'],
    subject: 'biology',
    description: 'Viruses may spread through route-specific pathways that can be reduced by suitable hygiene, ventilation, safe water, vector control, sterile equipment and vaccination.',
    prerequisiteConceptIds: ['concept-virus-structure'],
    relatedConceptIds: ['concept-virus-replication'],
    commonMisconceptions: ['Every virus spreads in the same way and can be stopped by one universal action.'],
    practicalRelevance: 'Supports evidence-based choices about hygiene, cough etiquette, ventilation, water safety, mosquito control and vaccination.',
    searchKeywords: ['transmission', 'respiratory', 'surface', 'water', 'mosquito', 'vaccination', 'prevention'],
  },
  {
    id: 'concept-mycelium',
    canonicalName: 'Hyphae and mycelium',
    aliases: ['fungal threads', 'hyphal network'],
    subject: 'biology',
    description: 'A hypha is a fungal thread, and many connected hyphae form a nutrient-absorbing mycelium.',
    prerequisiteConceptIds: ['concept-fungi'],
    relatedConceptIds: ['concept-decomposition'],
    commonMisconceptions: ['The visible mushroom is the entire fungus.'],
    practicalRelevance: 'Makes hidden fungal growth in soil, wood, and food easier to interpret.',
    searchKeywords: ['hypha', 'hyphae', 'mycelium', 'network', 'fungal growth'],
  },
  {
    id: 'concept-decomposition',
    canonicalName: 'Fungal decomposition',
    aliases: ['decomposer fungi', 'nutrient recycling'],
    subject: 'biology',
    description: 'Decomposer fungi break down dead organic matter and return nutrients to ecosystems.',
    prerequisiteConceptIds: ['concept-fungi'],
    relatedConceptIds: ['concept-mycelium'],
    commonMisconceptions: ['All fungi are harmful and have no ecosystem role.'],
    practicalRelevance: 'Explains composting, decay, soil nutrients, and forest nutrient cycles.',
    searchKeywords: ['decomposition', 'decomposer', 'dead matter', 'nutrients', 'forest'],
  },
  {
    id: 'concept-solubility',
    canonicalName: 'Solubility',
    aliases: ['soluble and insoluble', 'dissolving in water'],
    subject: 'science',
    description: 'The ability of a substance to dissolve in a solvent under stated conditions.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-solution', 'concept-mixture-observation'],
    commonMisconceptions: ['Dissolving means disappearing.'],
    practicalRelevance: 'Explains cooking, cleaning, water quality, and material separation.',
    searchKeywords: ['dissolve', 'soluble', 'insoluble', 'water'],
  },
  {
    id: 'concept-solution',
    canonicalName: 'Solution',
    aliases: ['solute and solvent', 'uniform mixture'],
    subject: 'chemistry',
    description: 'A mixture in which dissolved particles are distributed through a solvent.',
    prerequisiteConceptIds: ['concept-solubility'],
    relatedConceptIds: ['concept-mixture-observation'],
    commonMisconceptions: ['A clear solution contains no dissolved material.'],
    practicalRelevance: 'Supports preparation and interpretation of everyday mixtures.',
    searchKeywords: ['solute', 'solvent', 'clear mixture'],
  },
  {
    id: 'concept-mixture-observation',
    canonicalName: 'Observing mixtures',
    aliases: ['mixture evidence', 'settling floating separating'],
    subject: 'science',
    description: 'Use of visible evidence to distinguish dissolving, suspension, settling, and layering.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-solubility', 'concept-solution'],
    commonMisconceptions: ['Floating and dissolving describe the same process.'],
    practicalRelevance: 'Supports fair tests, filtration, and water-treatment reasoning.',
    searchKeywords: ['sediment', 'layer', 'cloudy', 'fair test'],
  },
  {
    id: 'concept-digestive-system',
    canonicalName: 'Human digestive system',
    aliases: ['digestive organs', 'human digestion'],
    subject: 'biology',
    description: 'The connected organs that break food down, absorb useful material, and remove solid waste.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-food-journey', 'concept-nutrient-absorption', 'concept-digestive-health'],
    commonMisconceptions: ['Digestion begins only after food reaches the stomach.'],
    practicalRelevance: 'Builds body awareness and explains how food supports growth and activity.',
    searchKeywords: ['mouth', 'esophagus', 'stomach', 'intestine'],
  },
  {
    id: 'concept-food-journey',
    canonicalName: 'Journey of food',
    aliases: ['digestive pathway', 'alimentary canal'],
    subject: 'biology',
    description: 'The ordered movement of food through the mouth, esophagus, stomach, intestines, rectum, and anus.',
    prerequisiteConceptIds: ['concept-digestive-system'],
    relatedConceptIds: ['concept-nutrient-absorption'],
    commonMisconceptions: ['Food passes through the liver, gallbladder, and pancreas.'],
    practicalRelevance: 'Helps students connect eating, swallowing, digestion, and waste removal.',
    searchKeywords: ['food pipe', 'peristalsis', 'chyme', 'waste'],
  },
  {
    id: 'concept-nutrient-absorption',
    canonicalName: 'Nutrient and water absorption',
    aliases: ['villi', 'absorption in intestines'],
    subject: 'biology',
    description: 'Movement of digested nutrients into blood through the small intestine and recovery of water in the large intestine.',
    prerequisiteConceptIds: ['concept-digestive-system', 'concept-food-journey'],
    relatedConceptIds: ['concept-digestive-health'],
    commonMisconceptions: ['The large intestine absorbs most food nutrients.'],
    practicalRelevance: 'Explains how food and water become useful to the whole body.',
    searchKeywords: ['small intestine', 'large intestine', 'blood', 'villi'],
  },
  {
    id: 'concept-digestive-health',
    canonicalName: 'Healthy digestion habits',
    aliases: ['digestive health', 'healthy eating habits'],
    subject: 'environmentalScience',
    description: 'Everyday choices that support digestion, including varied foods, water, chewing, hygiene, and movement.',
    prerequisiteConceptIds: ['concept-digestive-system'],
    relatedConceptIds: ['concept-nutrient-absorption'],
    commonMisconceptions: ['One food alone can keep the digestive system healthy.'],
    practicalRelevance: 'Supports informed choices about meals, hydration, exercise, and hand washing.',
    searchKeywords: ['fruit', 'vegetables', 'water', 'chewing', 'exercise'],
  },
  {
    id: 'concept-respiratory-system',
    canonicalName: 'Human respiratory system',
    aliases: ['breathing organs', 'respiratory organs'],
    subject: 'biology',
    description: 'The connected airway, lungs, and diaphragm that move air into and out of the body.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-breathing-mechanics', 'concept-gas-exchange'],
    commonMisconceptions: ['The lungs are the only organ involved in breathing.'],
    practicalRelevance: 'Builds body awareness and explains breathing rate changes during rest and exercise.',
    searchKeywords: ['lungs', 'trachea', 'diaphragm', 'bronchi'],
  },
  {
    id: 'concept-breathing-mechanics',
    canonicalName: 'Breathing mechanics',
    aliases: ['inhalation and exhalation', 'diaphragm movement'],
    subject: 'biology',
    description: 'The diaphragm and rib cage movements that change chest volume to draw air in and push it out.',
    prerequisiteConceptIds: ['concept-respiratory-system'],
    relatedConceptIds: ['concept-gas-exchange'],
    commonMisconceptions: ['The lungs actively pull themselves open to breathe in.'],
    practicalRelevance: 'Explains why deep breathing feels different from shallow breathing.',
    searchKeywords: ['diaphragm', 'rib cage', 'inhale', 'exhale'],
  },
  {
    id: 'concept-gas-exchange',
    canonicalName: 'Gas exchange',
    aliases: ['oxygen and carbon dioxide exchange', 'alveolar exchange'],
    subject: 'biology',
    description: 'The exchange of oxygen and carbon dioxide between air in the alveoli and blood in surrounding capillaries.',
    prerequisiteConceptIds: ['concept-respiratory-system'],
    relatedConceptIds: ['concept-breathing-mechanics'],
    commonMisconceptions: ['Gas exchange happens in the bronchi rather than the alveoli.'],
    practicalRelevance: 'Connects breathing to how the body gets oxygen and removes waste gas.',
    searchKeywords: ['alveoli', 'oxygen', 'carbon dioxide', 'capillaries'],
  },
  {
    id: 'concept-force-and-motion',
    canonicalName: 'Force and motion',
    aliases: ['effects of force on motion', 'push and pull'],
    subject: 'physics',
    description: 'A push or pull that can start, stop, speed up, slow down, or change the direction of a moving object.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-force-and-shape'],
    commonMisconceptions: ['A moving object needs a continuous force to keep moving.'],
    practicalRelevance: 'Explains everyday pushes and pulls: kicking a ball, braking, throwing harder, redirecting a rolling object.',
    searchKeywords: ['push', 'pull', 'speed', 'direction', 'brake'],
  },
  {
    id: 'concept-force-and-shape',
    canonicalName: 'Force and shape',
    aliases: ['deformation', 'elastic and non-elastic change'],
    subject: 'physics',
    description: 'A push or pull that changes an object\'s shape or size, which may or may not reverse once the force is removed.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-force-and-motion'],
    commonMisconceptions: ['Any shape change caused by force is permanent.'],
    practicalRelevance: 'Explains squeezing a sponge, stretching a rubber band, and denting a can.',
    searchKeywords: ['squeeze', 'stretch', 'elastic', 'deformation'],
  },
  {
    id: 'concept-acids-bases',
    canonicalName: 'Acids and bases',
    aliases: ['litmus test', 'acidic and basic solutions'],
    subject: 'chemistry',
    description: 'Acids turn blue litmus red and have a pH below 7; bases turn red litmus blue and have a pH above 7.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-ph-indicators', 'concept-neutralisation'],
    commonMisconceptions: ['A stronger acid has a higher pH.'],
    practicalRelevance: 'Explains household acids and bases, antacids, and reading product labels.',
    searchKeywords: ['acid', 'base', 'litmus', 'ph'],
  },
  {
    id: 'concept-ph-indicators',
    canonicalName: 'pH and indicators',
    aliases: ['universal indicator', 'ph scale'],
    subject: 'chemistry',
    description: 'A universal indicator shows a colour that maps to a solution\'s pH, from red (strong acid) through green (neutral) to violet (strong base).',
    prerequisiteConceptIds: ['concept-acids-bases'],
    relatedConceptIds: ['concept-neutralisation'],
    commonMisconceptions: ['Litmus and universal indicator give the same information.'],
    practicalRelevance: 'Explains soil-pH test kits, pool testing, and food acidity.',
    searchKeywords: ['ph scale', 'indicator', 'colour', 'neutral'],
  },
  {
    id: 'concept-neutralisation',
    canonicalName: 'Neutralisation',
    aliases: ['acid-base reaction', 'salt and water'],
    subject: 'chemistry',
    description: 'Adding a base to an acid raises the pH toward 7 and produces a salt and water.',
    prerequisiteConceptIds: ['concept-acids-bases', 'concept-ph-indicators'],
    relatedConceptIds: [],
    commonMisconceptions: ['Neutral means nothing happened, rather than acid and base cancelling to pH 7.'],
    practicalRelevance: 'Explains antacids relieving acidity and treating acidic soil with lime.',
    searchKeywords: ['neutralise', 'salt', 'water', 'ph 7'],
  },
  {
    id: 'concept-colour-names',
    canonicalName: 'Common colour names',
    aliases: ['colour recognition', 'naming colours'],
    subject: 'art',
    description:
      'Recognition and naming of red, blue, yellow, green, orange, purple, pink, brown, black, and white.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-colour-object-matching'],
    commonMisconceptions: ['A colour name can describe only one particular object.'],
    practicalRelevance:
      'Helps children describe surroundings, choose art materials, sort objects, and follow colour-based instructions.',
    searchKeywords: ['red', 'blue', 'yellow', 'green', 'colour names'],
  },
  {
    id: 'concept-colour-object-matching',
    canonicalName: 'Matching colours to objects',
    aliases: ['colour matching', 'sorting by colour'],
    subject: 'art',
    description:
      'Matching a spoken or written colour name to the visible colour shared by familiar objects.',
    prerequisiteConceptIds: ['concept-colour-names'],
    relatedConceptIds: ['concept-colour-names'],
    commonMisconceptions: ['Objects of the same kind must always have the same colour.'],
    practicalRelevance:
      'Supports visual comparison, sorting, drawing, painting, and precise everyday descriptions.',
    searchKeywords: ['match', 'sort', 'object colour', 'visual comparison'],
  },
  {
    id: 'concept-money-values',
    canonicalName: 'Money values',
    aliases: ['currency value', 'rupee values'],
    subject: 'mathematics',
    description: 'Understanding that coins and notes represent specific values that can be counted and compared.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-indian-coins-notes', 'concept-simple-shopping'],
    commonMisconceptions: ['All coins or notes have the same value.'],
    practicalRelevance: 'Supports early numeracy in shops, saving, and everyday transactions.',
    searchKeywords: ['rupee', 'value', 'counting money'],
  },
  {
    id: 'concept-indian-coins-notes',
    canonicalName: 'Indian coins and notes',
    aliases: ['Indian currency', 'coins and notes'],
    subject: 'mathematics',
    description: 'Recognition of common Indian currency forms and their written values.',
    prerequisiteConceptIds: ['concept-money-values'],
    relatedConceptIds: ['concept-simple-shopping'],
    commonMisconceptions: ['A larger-looking token always has a larger value.'],
    practicalRelevance: 'Helps children identify money used at home, school events, and shops.',
    searchKeywords: ['coin', 'note', 'currency', 'rupee'],
  },
  {
    id: 'concept-simple-shopping',
    canonicalName: 'Simple shopping with money',
    aliases: ['buying items', 'matching price'],
    subject: 'mathematics',
    description: 'Using money values to choose enough currency for simple priced items.',
    prerequisiteConceptIds: ['concept-money-values', 'concept-indian-coins-notes'],
    relatedConceptIds: [],
    commonMisconceptions: ['Any coin or note can buy any item.'],
    practicalRelevance: 'Connects counting and comparison to safe pretend shopping practice.',
    searchKeywords: ['shop', 'price', 'buy', 'pay'],
  },
  {
    id: 'concept-position-words',
    canonicalName: 'Position words',
    aliases: ['location words', 'spatial words'],
    subject: 'english',
    description: 'Words that describe where one object is in relation to another object.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-spatial-sentences', 'concept-preposition-use'],
    commonMisconceptions: ['In, on, under, and behind can be used interchangeably.'],
    practicalRelevance: 'Supports classroom instructions, reading, speaking, and writing.',
    searchKeywords: ['in', 'on', 'under', 'behind', 'between'],
  },
  {
    id: 'concept-spatial-sentences',
    canonicalName: 'Spatial sentences',
    aliases: ['location sentence', 'where sentence'],
    subject: 'english',
    description: 'Complete sentences that use position words to describe object location clearly.',
    prerequisiteConceptIds: ['concept-position-words'],
    relatedConceptIds: ['concept-preposition-use'],
    commonMisconceptions: ['A position word alone is a complete description.'],
    practicalRelevance: 'Helps children answer where questions in speech and writing.',
    searchKeywords: ['sentence', 'object', 'place', 'where'],
  },
  {
    id: 'concept-preposition-use',
    canonicalName: 'Preposition use',
    aliases: ['using prepositions', 'preposition grammar'],
    subject: 'english',
    description: 'Use of prepositions to show relationships between nouns or pronouns and other words.',
    prerequisiteConceptIds: ['concept-position-words'],
    relatedConceptIds: ['concept-spatial-sentences'],
    commonMisconceptions: ['Prepositions are labels to memorize without object relationships.'],
    practicalRelevance: 'Builds accurate speaking, reading comprehension, and writing.',
    searchKeywords: ['preposition', 'grammar', 'place', 'relationship'],
  },
  {
    id: 'concept-solar-system',
    canonicalName: 'Solar system',
    aliases: ['Sun and planets', 'planetary system'],
    subject: 'science',
    description: 'The Sun, planets, dwarf planets, moons, asteroids, and comets bound together by gravity.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-planet-order', 'concept-orbits-gravity', 'concept-planet-features'],
    commonMisconceptions: ['The solar system contains only planets.'],
    practicalRelevance: 'Supports astronomy, space missions, satellites, seasons, and night-sky observation.',
    searchKeywords: ['Sun', 'planet', 'moon', 'asteroid', 'comet'],
  },
  {
    id: 'concept-planet-order',
    canonicalName: 'Planet order',
    aliases: ['order of planets', 'Mercury to Neptune'],
    subject: 'science',
    description: 'The sequence of the eight planets from the Sun: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.',
    prerequisiteConceptIds: ['concept-solar-system'],
    relatedConceptIds: ['concept-planet-features'],
    commonMisconceptions: ['Pluto is one of the eight main planets.'],
    practicalRelevance: 'Creates a foundation for comparing distance, temperature, and orbital periods.',
    searchKeywords: ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
  },
  {
    id: 'concept-orbits-gravity',
    canonicalName: 'Orbits and gravity',
    aliases: ['planet orbits', 'gravity in space'],
    subject: 'physics',
    description: 'Gravity keeps planets and other bodies moving along orbital paths around larger bodies.',
    prerequisiteConceptIds: ['concept-solar-system'],
    relatedConceptIds: ['concept-planet-order'],
    commonMisconceptions: ['Planets move because there is no gravity in space.'],
    practicalRelevance: 'Explains satellites, moon motion, planetary years, and spaceflight paths.',
    searchKeywords: ['orbit', 'gravity', 'path', 'satellite'],
  },
  {
    id: 'concept-planet-features',
    canonicalName: 'Planet features',
    aliases: ['planet properties', 'rocky and gas planets'],
    subject: 'science',
    description: 'Observable and modelled differences between planets, including size, surface, atmosphere, rings, and moons.',
    prerequisiteConceptIds: ['concept-solar-system'],
    relatedConceptIds: ['concept-planet-order', 'concept-orbits-gravity'],
    commonMisconceptions: ['All planets have solid surfaces like Earth.'],
    practicalRelevance: 'Supports comparison, classification, and evidence-based space learning.',
    searchKeywords: ['rocky planet', 'gas giant', 'rings', 'atmosphere'],
  },
  ...GUIDED_LEARNING_CONCEPTS,
  ...INTERACTIVE_LEARNING_CONCEPTS,
];

export const CURRICULUM_CHAPTERS: CurriculumChapterRecord[] = [
  {
    id: 'chapter-cbse-c1-art-colours',
    courseId: 'course-cbse-c1-art',
    chapterNumber: 1,
    title: 'Learning of Colours',
    topicIds: ['topic-colour-recognition'],
    conceptIds: ['concept-colour-names', 'concept-colour-object-matching'],
    simulationIds: ['sim-c1-art-a01-learning-of-colours'],
  },
  {
    id: 'chapter-cbse-c1-math-money',
    courseId: 'course-cbse-c1-mathematics',
    chapterNumber: 1,
    title: 'Introduction to Money',
    topicIds: ['topic-money-values'],
    conceptIds: ['concept-money-values', 'concept-indian-coins-notes', 'concept-simple-shopping'],
    simulationIds: ['sim-c1-math-ch01-introduction-to-money'],
  },
  {
    id: 'chapter-cbse-c2-english-prepositions',
    courseId: 'course-cbse-c2-english',
    chapterNumber: 1,
    title: 'Prepositions',
    topicIds: ['topic-position-words'],
    conceptIds: ['concept-position-words', 'concept-spatial-sentences', 'concept-preposition-use'],
    simulationIds: ['sim-c2-english-ch01-prepositions'],
  },
  {
    id: 'chapter-cbse-c5-from-tasting-to-digesting',
    courseId: 'course-cbse-c5-environmental-science',
    chapterNumber: 3,
    title: 'From Tasting to Digesting',
    topicIds: ['topic-human-digestive-system'],
    conceptIds: [
      'concept-digestive-system',
      'concept-food-journey',
      'concept-nutrient-absorption',
      'concept-digestive-health',
    ],
    simulationIds: ['sim-c05-ch03-a02-introduction-of-digestive-system'],
  },
  {
    id: 'chapter-cbse-c5-water-experiments',
    courseId: 'course-cbse-c5-environmental-science',
    chapterNumber: 7,
    title: 'Experiments with Water',
    topicIds: ['topic-soluble-insoluble'],
    conceptIds: [
      'concept-solubility',
      'concept-solution',
      'concept-mixture-observation',
      'concept-density-and-buoyancy',
      'concept-buoyancy',
      'concept-density',
      'concept-displacement',
    ],
    simulationIds: [
      'sim-c05-ch07-a01-a-concept-about-what-floats-what-sinks',
      'sim-c05-ch07-a02-dead-sea-salt-water-and-its-effects',
      'sim-c05-ch07-a03-soluble-and-insoluble-substances',
    ],
  },
  {
    id: 'chapter-cbse-c6-food-sources',
    courseId: 'course-cbse-c6-science',
    chapterNumber: 1,
    title: 'Food: Where Does It Come From?',
    topicIds: ['topic-food-origins'],
    conceptIds: ['concept-food-sources', 'concept-plant-products', 'concept-animal-products', 'concept-edible-fungi'],
    simulationIds: ['sim-c06-ch01-a01-sources-of-food'],
  },
  {
    id: 'chapter-cbse-c7-reproduction-plants',
    courseId: 'course-cbse-c7-biology',
    chapterNumber: 12,
    title: 'Reproduction in Plants',
    topicIds: ['topic-pollination-growth-cycle'],
    conceptIds: ['concept-flower-structure', 'concept-pollination', 'concept-fertilisation', 'concept-seed-germination'],
    simulationIds: ['sim-pollination-001'],
  },
  {
    id: 'chapter-cbse-c7-respiration-organisms',
    courseId: 'course-cbse-c7-biology',
    chapterNumber: 10,
    title: 'Respiration in Organisms',
    topicIds: ['topic-respiration-in-organisms'],
    conceptIds: ['concept-respiratory-system', 'concept-breathing-mechanics', 'concept-gas-exchange'],
    simulationIds: ['sim-c07-ch10-a02-the-breathing-process-in-human'],
  },
  {
    id: 'chapter-cbse-c8-force-and-pressure',
    courseId: 'course-cbse-c8-physics',
    chapterNumber: 10,
    title: 'Force and Pressure',
    topicIds: ['topic-force-and-pressure'],
    conceptIds: ['concept-force-and-motion', 'concept-force-and-shape'],
    simulationIds: ['sim-c08-ch10-a02-the-effects-of-force-on-object-s-motion-and-shape'],
  },
  {
    id: 'chapter-cbse-c8-crop-production',
    courseId: 'course-cbse-c8-science',
    chapterNumber: 1,
    title: 'Crop Production and Management',
    topicIds: ['topic-irrigation-methods', 'topic-harvesting-threshing-storage'],
    conceptIds: [
      'concept-irrigation',
      'concept-irrigation-water-sources',
      'concept-irrigation-method-selection',
      'concept-crop-harvest-maturity',
      'concept-threshing-and-winnowing',
      'concept-grain-drying-and-storage',
    ],
    simulationIds: [
      'sim-c08-ch01-a03-irrigation-methods',
      'sim-c08-ch01-a05-harvesting-threshing-and-storage-of-crops',
    ],
  },
  {
    id: 'chapter-cbse-c8-microorganisms',
    courseId: 'course-cbse-c8-science',
    chapterNumber: 2,
    title: 'Microorganisms: Friend and Foe',
    topicIds: ['topic-virus-infection', 'topic-fungi-development'],
    conceptIds: [
      'concept-virus-structure',
      'concept-virus-replication',
      'concept-virus-transmission-prevention',
      'concept-fungi',
      'concept-mycelium',
      'concept-decomposition',
    ],
    simulationIds: [
      'sim-c08-ch02-a02-virus-introduction-spreading-and-its-effects',
      'sim-c08-ch02-a03-fungi-and-its-development',
    ],
  },
  {
    id: 'chapter-cbse-c8-solar-system',
    courseId: 'course-cbse-c8-science',
    chapterNumber: 17,
    title: 'Stars and the Solar System',
    topicIds: ['topic-solar-system'],
    conceptIds: ['concept-solar-system', 'concept-planet-order', 'concept-orbits-gravity', 'concept-planet-features'],
    simulationIds: ['sim-c8-10-science-solar-system'],
  },
  {
    id: 'chapter-cbse-c9-matter',
    courseId: 'course-cbse-c9-science',
    chapterNumber: 1,
    title: 'Matter in Our Surroundings',
    topicIds: ['topic-particle-model'],
    conceptIds: ['concept-states-of-matter', 'concept-particle-motion', 'concept-phase-change'],
    simulationIds: ['sim-c09-ch01-a02-states-of-matter'],
  },
  {
    id: 'chapter-cbse-c10-electricity',
    courseId: 'course-cbse-c10-physics',
    chapterNumber: 12,
    title: 'Electricity',
    topicIds: ['topic-current-resistance'],
    conceptIds: ['concept-electric-current', 'concept-closed-circuit', 'concept-resistance', 'concept-ohms-law'],
    simulationIds: ['sim-circuit-001'],
  },
  {
    id: 'chapter-cbse-c10-acids-bases-salts',
    courseId: 'course-cbse-c10-chemistry',
    chapterNumber: 2,
    title: 'Acids, Bases and Salts',
    topicIds: ['topic-acids-bases-salts'],
    conceptIds: ['concept-acids-bases', 'concept-ph-indicators', 'concept-neutralisation'],
    simulationIds: ['sim-c10-ch02-a01-introduction-to-acids-and-bases-and-litmus-test'],
  },
  ...GUIDED_CURRICULUM_CHAPTERS,
  ...INTERACTIVE_CURRICULUM_CHAPTERS,
];

export const COURSES: CourseRecord[] = [
  {
    id: 'course-cbse-c1-art',
    title: 'CBSE Class 1 Art',
    board: 'cbse',
    classLevel: 1,
    gradeBand: 'class1To2',
    subject: 'art',
    description:
      'Foundational visual-art learning through recognising, naming, matching, and using common colours.',
    chapterIds: ['chapter-cbse-c1-art-colours'],
    conceptIds: ['concept-colour-names', 'concept-colour-object-matching'],
    simulationIds: ['sim-c1-art-a01-learning-of-colours'],
    searchKeywords: ['class 1', 'art', 'colours', 'colour recognition', 'colour matching'],
  },
  {
    id: 'course-cbse-c1-mathematics',
    title: 'CBSE Class 1 Mathematics',
    board: 'cbse',
    classLevel: 1,
    gradeBand: 'class1To2',
    subject: 'mathematics',
    description: 'Early mathematics built around counting, comparison, money, and everyday number sense.',
    chapterIds: ['chapter-cbse-c1-math-money'],
    conceptIds: ['concept-money-values', 'concept-indian-coins-notes', 'concept-simple-shopping'],
    simulationIds: ['sim-c1-math-ch01-introduction-to-money'],
    searchKeywords: ['class 1', 'money', 'coins', 'notes', 'rupees'],
  },
  {
    id: 'course-cbse-c2-english',
    title: 'CBSE Class 2 English',
    board: 'cbse',
    classLevel: 2,
    gradeBand: 'class1To2',
    subject: 'english',
    description: 'Foundational English language practice through listening, speaking, grammar, and everyday sentences.',
    chapterIds: ['chapter-cbse-c2-english-prepositions'],
    conceptIds: ['concept-position-words', 'concept-spatial-sentences', 'concept-preposition-use'],
    simulationIds: ['sim-c2-english-ch01-prepositions'],
    searchKeywords: ['class 2', 'english', 'prepositions', 'position words'],
  },
  {
    id: 'course-cbse-c5-environmental-science',
    title: 'CBSE Class 5 Environmental Studies',
    board: 'cbse',
    classLevel: 5,
    gradeBand: 'class3To5',
    subject: 'environmentalScience',
    description: 'Observation-led environmental science connecting the human body, health, everyday materials, and water.',
    chapterIds: [
      'chapter-cbse-c5-from-tasting-to-digesting',
      'chapter-cbse-c5-water-experiments',
      ...GUIDED_CLASS5_CHAPTER_IDS,
    ],
    conceptIds: [
      'concept-digestive-system',
      'concept-food-journey',
      'concept-nutrient-absorption',
      'concept-digestive-health',
      'concept-solubility',
      'concept-solution',
      'concept-mixture-observation',
      'concept-buoyancy',
      'concept-density',
      'concept-displacement',
      ...GUIDED_CLASS5_CONCEPT_IDS,
    ],
    simulationIds: [
      'sim-c05-ch03-a02-introduction-of-digestive-system',
      'sim-c05-ch07-a01-a-concept-about-what-floats-what-sinks',
      'sim-c05-ch07-a03-soluble-and-insoluble-substances',
      'sim-c05-ch07-a02-dead-sea-salt-water-and-its-effects',
      ...GUIDED_CLASS5_SIMULATION_IDS,
    ],
    searchKeywords: [
      'class 5',
      'EVS',
      'digestive system',
      'water experiments',
      'food preservation',
      'plants',
      'malaria',
      'heritage',
    ],
  },
  {
    id: 'course-cbse-c6-science',
    title: 'CBSE Class 6 Science',
    board: 'cbse',
    classLevel: 6,
    gradeBand: 'class6To8',
    subject: 'science',
    description: 'Foundational science connecting food, living sources, and daily observation.',
    chapterIds: [
      'chapter-cbse-c6-food-sources',
      ...INTERACTIVE_CLASS6_CHAPTER_IDS,
      ...GUIDED_CLASS6_CHAPTER_IDS,
    ],
    conceptIds: [
      'concept-food-sources',
      'concept-plant-products',
      'concept-animal-products',
      'concept-edible-fungi',
      ...INTERACTIVE_CLASS6_CONCEPT_IDS,
      ...GUIDED_CLASS6_CONCEPT_IDS,
    ],
    simulationIds: [
      'sim-c06-ch01-a01-sources-of-food',
      ...INTERACTIVE_CLASS6_SIMULATION_IDS,
      ...GUIDED_CLASS6_SIMULATION_IDS,
    ],
    searchKeywords: ['class 6', 'food sources', 'ingredients', 'cotton', 'ginning', 'fibre'],
  },
  {
    id: 'course-cbse-c7-biology',
    title: 'CBSE Class 7 Biology',
    board: 'cbse',
    classLevel: 7,
    gradeBand: 'class6To8',
    subject: 'biology',
    description: 'Life-science concepts made visible through wool processing, plant structure, reproduction, and human respiration.',
    chapterIds: [
      ...GUIDED_CLASS7_CHAPTER_IDS,
      'chapter-cbse-c7-reproduction-plants',
      'chapter-cbse-c7-respiration-organisms',
    ],
    conceptIds: [
      'concept-flower-structure',
      'concept-pollination',
      'concept-fertilisation',
      'concept-seed-germination',
      'concept-respiratory-system',
      'concept-breathing-mechanics',
      'concept-gas-exchange',
      ...GUIDED_CLASS7_CONCEPT_IDS,
    ],
    simulationIds: [
      ...GUIDED_CLASS7_SIMULATION_IDS,
      'sim-pollination-001',
      'sim-c07-ch10-a02-the-breathing-process-in-human',
    ],
    searchKeywords: [
      'class 7',
      'plants',
      'pollination',
      'respiration',
      'breathing',
      'lungs',
      'wool',
      'fleece',
      'shearing',
      'scouring',
      'carding',
      'combing',
      'sliver',
      'roving',
      'spinning',
      'winding',
      'yarn',
    ],
  },
  {
    id: 'course-cbse-c8-physics',
    title: 'CBSE Class 8 Physics',
    board: 'cbse',
    classLevel: 8,
    gradeBand: 'class6To8',
    subject: 'physics',
    description: 'Hands-on physical science exploring how force changes motion and shape.',
    chapterIds: ['chapter-cbse-c8-force-and-pressure'],
    conceptIds: ['concept-force-and-motion', 'concept-force-and-shape'],
    simulationIds: ['sim-c08-ch10-a02-the-effects-of-force-on-object-s-motion-and-shape'],
    searchKeywords: ['class 8', 'force', 'pressure', 'motion', 'shape'],
  },
  {
    id: 'course-cbse-c8-science',
    title: 'CBSE Class 8 Science',
    board: 'cbse',
    classLevel: 8,
    gradeBand: 'class6To8',
    subject: 'science',
    description: 'Middle-school science connecting space, matter, force, living systems, and technology through observable models.',
    chapterIds: ['chapter-cbse-c8-crop-production', 'chapter-cbse-c8-microorganisms', 'chapter-cbse-c8-solar-system'],
    conceptIds: [
      'concept-irrigation',
      'concept-irrigation-water-sources',
      'concept-irrigation-method-selection',
      'concept-crop-harvest-maturity',
      'concept-threshing-and-winnowing',
      'concept-grain-drying-and-storage',
      'concept-virus-structure',
      'concept-virus-replication',
      'concept-virus-transmission-prevention',
      'concept-fungi',
      'concept-mycelium',
      'concept-decomposition',
      'concept-solar-system',
      'concept-planet-order',
      'concept-orbits-gravity',
      'concept-planet-features',
    ],
    simulationIds: [
      'sim-c08-ch01-a03-irrigation-methods',
      'sim-c08-ch01-a05-harvesting-threshing-and-storage-of-crops',
      'sim-c08-ch02-a02-virus-introduction-spreading-and-its-effects',
      'sim-c08-ch02-a03-fungi-and-its-development',
      'sim-c8-10-science-solar-system',
    ],
    searchKeywords: ['class 8', 'irrigation', 'sprinkler', 'drip', 'crop production', 'harvesting', 'threshing', 'winnowing', 'grain drying', 'grain storage', 'granary', 'silo', 'virus', 'viral transmission', 'host cell', 'fungi', 'mycelium', 'microorganisms', 'solar system', 'planets', 'space'],
  },
  {
    id: 'course-cbse-c9-science',
    title: 'CBSE Class 9 Science',
    board: 'cbse',
    classLevel: 9,
    gradeBand: 'class9To10',
    subject: 'chemistry',
    description: 'Microscopic models for matter, particles, and energy-driven state change.',
    chapterIds: ['chapter-cbse-c9-matter'],
    conceptIds: ['concept-states-of-matter', 'concept-particle-motion', 'concept-phase-change'],
    simulationIds: ['sim-c09-ch01-a02-states-of-matter'],
    searchKeywords: ['class 9', 'matter', 'particle model'],
  },
  {
    id: 'course-cbse-c10-physics',
    title: 'CBSE Class 10 Physics',
    board: 'cbse',
    classLevel: 10,
    gradeBand: 'class9To10',
    subject: 'physics',
    description: 'Interactive physical science focused on electricity, current, and resistance.',
    chapterIds: ['chapter-cbse-c10-electricity'],
    conceptIds: ['concept-electric-current', 'concept-closed-circuit', 'concept-resistance', 'concept-ohms-law'],
    simulationIds: ['sim-circuit-001'],
    searchKeywords: ['class 10', 'electricity', 'Ohms law'],
  },
  {
    id: 'course-cbse-c10-chemistry',
    title: 'CBSE Class 10 Chemistry',
    board: 'cbse',
    classLevel: 10,
    gradeBand: 'class9To10',
    subject: 'chemistry',
    description: 'Interactive chemistry focused on acids, bases, the pH scale, and neutralisation.',
    chapterIds: ['chapter-cbse-c10-acids-bases-salts'],
    conceptIds: ['concept-acids-bases', 'concept-ph-indicators', 'concept-neutralisation'],
    simulationIds: ['sim-c10-ch02-a01-introduction-to-acids-and-bases-and-litmus-test'],
    searchKeywords: ['class 10', 'acids', 'bases', 'ph', 'neutralisation'],
  },
];

const CLASS_LEVELS_BY_GRADE_BAND: Readonly<Record<GradeBand, readonly number[]>> = {
  kindergarten: [],
  class1To2: [1, 2],
  class3To5: [3, 4, 5],
  class6To8: [6, 7, 8],
  class9To10: [9, 10],
  class11To12: [11, 12],
};

function encodedClassLevels(identifier: string): number[] | undefined {
  const canonical = identifier.replace(/^sim-/, '');
  const match = /^c(\d{1,2})(?:-(\d{1,2}))?(?:-|$)/.exec(canonical);
  if (!match) return undefined;
  const first = Number(match[1]);
  const last = Number(match[2] ?? match[1]);
  if (
    !Number.isInteger(first)
    || !Number.isInteger(last)
    || first < 1
    || last > 12
    || last < first
  ) {
    return undefined;
  }
  return Array.from({ length: last - first + 1 }, (_, index) => first + index);
}

/**
 * Resolves the exact curriculum class for a canonical simulation module.
 * The canonical `cNN`/`cN-M` identity takes precedence, followed by explicit
 * course links, with grade-band expansion reserved for genuinely multi-grade
 * modules whose stable identity does not encode an exact class or range.
 */
export function classLevelsForSimulation(
  module: SimulationModuleRecord,
  courses: readonly CourseRecord[] = COURSES,
): number[] {
  for (const identifier of [module.id, module.slug]) {
    const encodedLevels = encodedClassLevels(identifier);
    if (encodedLevels) return encodedLevels;
  }

  const linkedLevels = courses
    .filter(course => course.simulationIds.includes(module.id))
    .map(course => course.classLevel);
  if (linkedLevels.length > 0) {
    return [...new Set(linkedLevels)].sort((left, right) => left - right);
  }

  return [...new Set(
    module.gradeBands.flatMap(gradeBand => CLASS_LEVELS_BY_GRADE_BAND[gradeBand]),
  )].sort((left, right) => left - right);
}
