import type {
  CourseRecord,
  CurriculumChapterRecord,
  LearningConceptRecord,
} from '../../simulation-schema/src/index';

export const LEARNING_CONCEPTS: LearningConceptRecord[] = [
  {
    id: 'concept-flower-structure',
    canonicalName: 'Flower structure',
    aliases: ['parts of a flower', 'stamen and stigma'],
    subject: 'biology',
    description: 'The reproductive structures of a flower and the role each part plays.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-pollination', 'concept-fertilisation'],
    commonMisconceptions: ['All visible flower parts have the same reproductive role.'],
    practicalRelevance: 'Supports observation of flowering crops and plant reproduction.',
    searchKeywords: ['anther', 'stigma', 'ovary', 'petal'],
  },
  {
    id: 'concept-pollination',
    canonicalName: 'Pollination',
    aliases: ['pollen transfer', 'cross-pollination'],
    subject: 'biology',
    description: 'Transfer of pollen from an anther to a compatible stigma.',
    prerequisiteConceptIds: ['concept-flower-structure'],
    relatedConceptIds: ['concept-fertilisation', 'concept-seed-germination'],
    commonMisconceptions: ['Pollination and fertilisation are the same event.'],
    practicalRelevance: 'Explains pollinator value in gardens, orchards, and food production.',
    searchKeywords: ['bee', 'pollinator', 'pollen', 'stigma'],
  },
  {
    id: 'concept-fertilisation',
    canonicalName: 'Fertilisation',
    aliases: ['plant fertilization', 'fusion of gametes'],
    subject: 'biology',
    description: 'Fusion of reproductive cells after successful pollination, leading toward seed formation.',
    prerequisiteConceptIds: ['concept-pollination'],
    relatedConceptIds: ['concept-flower-structure', 'concept-seed-germination'],
    commonMisconceptions: ['A seed forms immediately when pollen touches a flower.'],
    practicalRelevance: 'Connects flower biology to fruit and seed production.',
    searchKeywords: ['ovule', 'ovary', 'seed formation'],
  },
  {
    id: 'concept-seed-germination',
    canonicalName: 'Seed germination',
    aliases: ['germination', 'seed sprouting'],
    subject: 'biology',
    description: 'Growth of a seed into a seedling when water, oxygen, and temperature are suitable.',
    prerequisiteConceptIds: ['concept-fertilisation'],
    relatedConceptIds: ['concept-pollination'],
    commonMisconceptions: ['Seeds germinate without suitable environmental conditions.'],
    practicalRelevance: 'Informs crop sowing, kitchen gardens, and seed care.',
    searchKeywords: ['seedling', 'sprout', 'plant growth'],
  },
  {
    id: 'concept-electric-current',
    canonicalName: 'Electric current',
    aliases: ['current', 'flow of charge'],
    subject: 'physics',
    description: 'The rate of electric charge flow through a conducting path.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-closed-circuit', 'concept-resistance', 'concept-ohms-law'],
    commonMisconceptions: ['Current is consumed by a bulb.'],
    practicalRelevance: 'Supports safe reasoning about appliances, batteries, and circuits.',
    searchKeywords: ['charge', 'ampere', 'electron flow'],
  },
  {
    id: 'concept-closed-circuit',
    canonicalName: 'Closed circuit',
    aliases: ['complete circuit', 'circuit path'],
    subject: 'physics',
    description: 'An unbroken conducting path that allows electric current to flow.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-electric-current', 'concept-resistance'],
    commonMisconceptions: ['A switch creates current rather than completing a path.'],
    practicalRelevance: 'Explains switches, torch circuits, and basic fault finding.',
    searchKeywords: ['switch', 'battery', 'bulb', 'wire'],
  },
  {
    id: 'concept-resistance',
    canonicalName: 'Electrical resistance',
    aliases: ['resistance', 'resistor'],
    subject: 'physics',
    description: 'Opposition to charge flow, measured in ohms.',
    prerequisiteConceptIds: ['concept-electric-current'],
    relatedConceptIds: ['concept-ohms-law', 'concept-closed-circuit'],
    commonMisconceptions: ['Higher resistance makes current move faster.'],
    practicalRelevance: 'Helps select components and understand heating and brightness.',
    searchKeywords: ['ohm', 'resistor value', 'brightness'],
  },
  {
    id: 'concept-ohms-law',
    canonicalName: "Ohm's law",
    aliases: ['V equals IR', 'voltage current resistance'],
    subject: 'physics',
    description: 'The quantitative relationship between voltage, current, and resistance.',
    prerequisiteConceptIds: ['concept-electric-current', 'concept-resistance'],
    relatedConceptIds: ['concept-closed-circuit'],
    commonMisconceptions: ['Voltage and current are interchangeable quantities.'],
    practicalRelevance: 'Enables prediction of current in simple electrical systems.',
    searchKeywords: ['V=IR', 'voltage', 'current calculation'],
  },
  {
    id: 'concept-states-of-matter',
    canonicalName: 'States of matter',
    aliases: ['solid liquid gas', 'phases of matter'],
    subject: 'chemistry',
    description: 'Observable forms of matter produced by different particle arrangements and energies.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-particle-motion', 'concept-phase-change'],
    commonMisconceptions: ['Particles exist only in gases.'],
    practicalRelevance: 'Explains everyday materials, weather, cooking, and storage.',
    searchKeywords: ['solid', 'liquid', 'gas', 'matter'],
  },
  {
    id: 'concept-particle-motion',
    canonicalName: 'Particle motion',
    aliases: ['kinetic particle theory', 'particle movement'],
    subject: 'physics',
    description: 'Microscopic particle speed, spacing, and movement in different states of matter.',
    prerequisiteConceptIds: ['concept-states-of-matter'],
    relatedConceptIds: ['concept-phase-change'],
    commonMisconceptions: ['Particles in solids do not move.'],
    practicalRelevance: 'Builds a mental model for diffusion, heating, and cooling.',
    searchKeywords: ['kinetic energy', 'spacing', 'vibration'],
  },
  {
    id: 'concept-phase-change',
    canonicalName: 'Phase change',
    aliases: ['change of state', 'melting boiling condensation'],
    subject: 'chemistry',
    description: 'A reversible change between states caused by energy transfer.',
    prerequisiteConceptIds: ['concept-states-of-matter', 'concept-particle-motion'],
    relatedConceptIds: [],
    commonMisconceptions: ['Heating creates new particles.'],
    practicalRelevance: 'Explains refrigeration, rainfall, evaporation, and cooking.',
    searchKeywords: ['melting', 'boiling', 'freezing', 'condensation'],
  },
  {
    id: 'concept-food-sources',
    canonicalName: 'Sources of food',
    aliases: ['food origins', 'where food comes from'],
    subject: 'science',
    description: 'Classification of food ingredients by the living source from which they are obtained.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-plant-products', 'concept-animal-products', 'concept-edible-fungi'],
    commonMisconceptions: ['Food source categories are the same as food groups.'],
    practicalRelevance: 'Connects meals and markets to farms, animals, and fungi.',
    searchKeywords: ['ingredients', 'origin', 'meal'],
  },
  {
    id: 'concept-plant-products',
    canonicalName: 'Plant food products',
    aliases: ['plant sources', 'foods from plants'],
    subject: 'biology',
    description: 'Foods obtained from plant parts including seeds, fruits, leaves, roots, and stems.',
    prerequisiteConceptIds: ['concept-food-sources'],
    relatedConceptIds: ['concept-animal-products', 'concept-edible-fungi'],
    commonMisconceptions: ['Only green vegetables are plant products.'],
    practicalRelevance: 'Supports nutrition, farming, and ingredient-label discussions.',
    searchKeywords: ['grain', 'pulse', 'fruit', 'vegetable'],
  },
  {
    id: 'concept-animal-products',
    canonicalName: 'Animal food products',
    aliases: ['animal sources', 'foods from animals'],
    subject: 'biology',
    description: 'Foods obtained from animals, including milk, eggs, honey, meat, and fish.',
    prerequisiteConceptIds: ['concept-food-sources'],
    relatedConceptIds: ['concept-plant-products', 'concept-edible-fungi'],
    commonMisconceptions: ['Milk and honey are plant products.'],
    practicalRelevance: 'Links food choices to dairy, poultry, beekeeping, and fisheries.',
    searchKeywords: ['milk', 'egg', 'honey', 'fish'],
  },
  {
    id: 'concept-edible-fungi',
    canonicalName: 'Edible fungi',
    aliases: ['mushrooms', 'fungal food sources'],
    subject: 'biology',
    description: 'Fungi used as food and their distinction from plants and animals.',
    prerequisiteConceptIds: ['concept-food-sources'],
    relatedConceptIds: ['concept-plant-products', 'concept-animal-products'],
    commonMisconceptions: ['Mushrooms are plants.'],
    practicalRelevance: 'Supports accurate food classification and safe food-source discussion.',
    searchKeywords: ['fungus', 'mushroom', 'decomposer'],
  },
  {
    id: 'concept-solubility',
    canonicalName: 'Solubility',
    aliases: ['soluble and insoluble', 'dissolving in water'],
    subject: 'science',
    description: 'The ability of a substance to dissolve in a solvent under stated conditions.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-solution', 'concept-mixture-observation'],
    commonMisconceptions: ['Dissolving means disappearing.'],
    practicalRelevance: 'Explains cooking, cleaning, water quality, and material separation.',
    searchKeywords: ['dissolve', 'soluble', 'insoluble', 'water'],
  },
  {
    id: 'concept-solution',
    canonicalName: 'Solution',
    aliases: ['solute and solvent', 'uniform mixture'],
    subject: 'chemistry',
    description: 'A mixture in which dissolved particles are distributed through a solvent.',
    prerequisiteConceptIds: ['concept-solubility'],
    relatedConceptIds: ['concept-mixture-observation'],
    commonMisconceptions: ['A clear solution contains no dissolved material.'],
    practicalRelevance: 'Supports preparation and interpretation of everyday mixtures.',
    searchKeywords: ['solute', 'solvent', 'clear mixture'],
  },
  {
    id: 'concept-mixture-observation',
    canonicalName: 'Observing mixtures',
    aliases: ['mixture evidence', 'settling floating separating'],
    subject: 'science',
    description: 'Use of visible evidence to distinguish dissolving, suspension, settling, and layering.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-solubility', 'concept-solution'],
    commonMisconceptions: ['Floating and dissolving describe the same process.'],
    practicalRelevance: 'Supports fair tests, filtration, and water-treatment reasoning.',
    searchKeywords: ['sediment', 'layer', 'cloudy', 'fair test'],
  },
  {
    id: 'concept-digestive-system',
    canonicalName: 'Human digestive system',
    aliases: ['digestive organs', 'human digestion'],
    subject: 'biology',
    description: 'The connected organs that break food down, absorb useful material, and remove solid waste.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-food-journey', 'concept-nutrient-absorption', 'concept-digestive-health'],
    commonMisconceptions: ['Digestion begins only after food reaches the stomach.'],
    practicalRelevance: 'Builds body awareness and explains how food supports growth and activity.',
    searchKeywords: ['mouth', 'esophagus', 'stomach', 'intestine'],
  },
  {
    id: 'concept-food-journey',
    canonicalName: 'Journey of food',
    aliases: ['digestive pathway', 'alimentary canal'],
    subject: 'biology',
    description: 'The ordered movement of food through the mouth, esophagus, stomach, intestines, rectum, and anus.',
    prerequisiteConceptIds: ['concept-digestive-system'],
    relatedConceptIds: ['concept-nutrient-absorption'],
    commonMisconceptions: ['Food passes through the liver, gallbladder, and pancreas.'],
    practicalRelevance: 'Helps students connect eating, swallowing, digestion, and waste removal.',
    searchKeywords: ['food pipe', 'peristalsis', 'chyme', 'waste'],
  },
  {
    id: 'concept-nutrient-absorption',
    canonicalName: 'Nutrient and water absorption',
    aliases: ['villi', 'absorption in intestines'],
    subject: 'biology',
    description: 'Movement of digested nutrients into blood through the small intestine and recovery of water in the large intestine.',
    prerequisiteConceptIds: ['concept-digestive-system', 'concept-food-journey'],
    relatedConceptIds: ['concept-digestive-health'],
    commonMisconceptions: ['The large intestine absorbs most food nutrients.'],
    practicalRelevance: 'Explains how food and water become useful to the whole body.',
    searchKeywords: ['small intestine', 'large intestine', 'blood', 'villi'],
  },
  {
    id: 'concept-digestive-health',
    canonicalName: 'Healthy digestion habits',
    aliases: ['digestive health', 'healthy eating habits'],
    subject: 'environmentalScience',
    description: 'Everyday choices that support digestion, including varied foods, water, chewing, hygiene, and movement.',
    prerequisiteConceptIds: ['concept-digestive-system'],
    relatedConceptIds: ['concept-nutrient-absorption'],
    commonMisconceptions: ['One food alone can keep the digestive system healthy.'],
    practicalRelevance: 'Supports informed choices about meals, hydration, exercise, and hand washing.',
    searchKeywords: ['fruit', 'vegetables', 'water', 'chewing', 'exercise'],
  },
  {
    id: 'concept-respiratory-system',
    canonicalName: 'Human respiratory system',
    aliases: ['breathing organs', 'respiratory organs'],
    subject: 'biology',
    description: 'The connected airway, lungs, and diaphragm that move air into and out of the body.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-breathing-mechanics', 'concept-gas-exchange'],
    commonMisconceptions: ['The lungs are the only organ involved in breathing.'],
    practicalRelevance: 'Builds body awareness and explains breathing rate changes during rest and exercise.',
    searchKeywords: ['lungs', 'trachea', 'diaphragm', 'bronchi'],
  },
  {
    id: 'concept-breathing-mechanics',
    canonicalName: 'Breathing mechanics',
    aliases: ['inhalation and exhalation', 'diaphragm movement'],
    subject: 'biology',
    description: 'The diaphragm and rib cage movements that change chest volume to draw air in and push it out.',
    prerequisiteConceptIds: ['concept-respiratory-system'],
    relatedConceptIds: ['concept-gas-exchange'],
    commonMisconceptions: ['The lungs actively pull themselves open to breathe in.'],
    practicalRelevance: 'Explains why deep breathing feels different from shallow breathing.',
    searchKeywords: ['diaphragm', 'rib cage', 'inhale', 'exhale'],
  },
  {
    id: 'concept-gas-exchange',
    canonicalName: 'Gas exchange',
    aliases: ['oxygen and carbon dioxide exchange', 'alveolar exchange'],
    subject: 'biology',
    description: 'The exchange of oxygen and carbon dioxide between air in the alveoli and blood in surrounding capillaries.',
    prerequisiteConceptIds: ['concept-respiratory-system'],
    relatedConceptIds: ['concept-breathing-mechanics'],
    commonMisconceptions: ['Gas exchange happens in the bronchi rather than the alveoli.'],
    practicalRelevance: 'Connects breathing to how the body gets oxygen and removes waste gas.',
    searchKeywords: ['alveoli', 'oxygen', 'carbon dioxide', 'capillaries'],
  },
  {
    id: 'concept-force-and-motion',
    canonicalName: 'Force and motion',
    aliases: ['effects of force on motion', 'push and pull'],
    subject: 'physics',
    description: 'A push or pull that can start, stop, speed up, slow down, or change the direction of a moving object.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-force-and-shape'],
    commonMisconceptions: ['A moving object needs a continuous force to keep moving.'],
    practicalRelevance: 'Explains everyday pushes and pulls: kicking a ball, braking, throwing harder, redirecting a rolling object.',
    searchKeywords: ['push', 'pull', 'speed', 'direction', 'brake'],
  },
  {
    id: 'concept-force-and-shape',
    canonicalName: 'Force and shape',
    aliases: ['deformation', 'elastic and non-elastic change'],
    subject: 'physics',
    description: 'A push or pull that changes an object\'s shape or size, which may or may not reverse once the force is removed.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-force-and-motion'],
    commonMisconceptions: ['Any shape change caused by force is permanent.'],
    practicalRelevance: 'Explains squeezing a sponge, stretching a rubber band, and denting a can.',
    searchKeywords: ['squeeze', 'stretch', 'elastic', 'deformation'],
  },
  {
    id: 'concept-acids-bases',
    canonicalName: 'Acids and bases',
    aliases: ['litmus test', 'acidic and basic solutions'],
    subject: 'chemistry',
    description: 'Acids turn blue litmus red and have a pH below 7; bases turn red litmus blue and have a pH above 7.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-ph-indicators', 'concept-neutralisation'],
    commonMisconceptions: ['A stronger acid has a higher pH.'],
    practicalRelevance: 'Explains household acids and bases, antacids, and reading product labels.',
    searchKeywords: ['acid', 'base', 'litmus', 'ph'],
  },
  {
    id: 'concept-ph-indicators',
    canonicalName: 'pH and indicators',
    aliases: ['universal indicator', 'ph scale'],
    subject: 'chemistry',
    description: 'A universal indicator shows a colour that maps to a solution\'s pH, from red (strong acid) through green (neutral) to violet (strong base).',
    prerequisiteConceptIds: ['concept-acids-bases'],
    relatedConceptIds: ['concept-neutralisation'],
    commonMisconceptions: ['Litmus and universal indicator give the same information.'],
    practicalRelevance: 'Explains soil-pH test kits, pool testing, and food acidity.',
    searchKeywords: ['ph scale', 'indicator', 'colour', 'neutral'],
  },
  {
    id: 'concept-neutralisation',
    canonicalName: 'Neutralisation',
    aliases: ['acid-base reaction', 'salt and water'],
    subject: 'chemistry',
    description: 'Adding a base to an acid raises the pH toward 7 and produces a salt and water.',
    prerequisiteConceptIds: ['concept-acids-bases', 'concept-ph-indicators'],
    relatedConceptIds: [],
    commonMisconceptions: ['Neutral means nothing happened, rather than acid and base cancelling to pH 7.'],
    practicalRelevance: 'Explains antacids relieving acidity and treating acidic soil with lime.',
    searchKeywords: ['neutralise', 'salt', 'water', 'ph 7'],
  },
];

export const CURRICULUM_CHAPTERS: CurriculumChapterRecord[] = [
  {
    id: 'chapter-cbse-c5-from-tasting-to-digesting',
    courseId: 'course-cbse-c5-environmental-science',
    chapterNumber: 3,
    title: 'From Tasting to Digesting',
    topicIds: ['topic-human-digestive-system'],
    conceptIds: [
      'concept-digestive-system',
      'concept-food-journey',
      'concept-nutrient-absorption',
      'concept-digestive-health',
    ],
    simulationIds: ['sim-c05-ch03-a02-introduction-of-digestive-system'],
  },
  {
    id: 'chapter-cbse-c5-water-experiments',
    courseId: 'course-cbse-c5-environmental-science',
    chapterNumber: 7,
    title: 'Experiments with Water',
    topicIds: ['topic-soluble-insoluble'],
    conceptIds: ['concept-solubility', 'concept-solution', 'concept-mixture-observation'],
    simulationIds: ['sim-c05-ch07-a03-soluble-and-insoluble-substances'],
  },
  {
    id: 'chapter-cbse-c6-food-sources',
    courseId: 'course-cbse-c6-science',
    chapterNumber: 1,
    title: 'Food: Where Does It Come From?',
    topicIds: ['topic-food-origins'],
    conceptIds: ['concept-food-sources', 'concept-plant-products', 'concept-animal-products', 'concept-edible-fungi'],
    simulationIds: ['sim-c06-ch01-a01-sources-of-food'],
  },
  {
    id: 'chapter-cbse-c7-reproduction-plants',
    courseId: 'course-cbse-c7-biology',
    chapterNumber: 12,
    title: 'Reproduction in Plants',
    topicIds: ['topic-pollination-growth-cycle'],
    conceptIds: ['concept-flower-structure', 'concept-pollination', 'concept-fertilisation', 'concept-seed-germination'],
    simulationIds: ['sim-pollination-001'],
  },
  {
    id: 'chapter-cbse-c7-respiration-organisms',
    courseId: 'course-cbse-c7-biology',
    chapterNumber: 10,
    title: 'Respiration in Organisms',
    topicIds: ['topic-respiration-in-organisms'],
    conceptIds: ['concept-respiratory-system', 'concept-breathing-mechanics', 'concept-gas-exchange'],
    simulationIds: ['sim-c07-ch10-a02-the-breathing-process-in-human'],
  },
  {
    id: 'chapter-cbse-c8-force-and-pressure',
    courseId: 'course-cbse-c8-physics',
    chapterNumber: 10,
    title: 'Force and Pressure',
    topicIds: ['topic-force-and-pressure'],
    conceptIds: ['concept-force-and-motion', 'concept-force-and-shape'],
    simulationIds: ['sim-c08-ch10-a02-the-effects-of-force-on-object-s-motion-and-shape'],
  },
  {
    id: 'chapter-cbse-c9-matter',
    courseId: 'course-cbse-c9-science',
    chapterNumber: 1,
    title: 'Matter in Our Surroundings',
    topicIds: ['topic-particle-model'],
    conceptIds: ['concept-states-of-matter', 'concept-particle-motion', 'concept-phase-change'],
    simulationIds: ['sim-c09-ch01-a02-states-of-matter'],
  },
  {
    id: 'chapter-cbse-c10-electricity',
    courseId: 'course-cbse-c10-physics',
    chapterNumber: 12,
    title: 'Electricity',
    topicIds: ['topic-current-resistance'],
    conceptIds: ['concept-electric-current', 'concept-closed-circuit', 'concept-resistance', 'concept-ohms-law'],
    simulationIds: ['sim-circuit-001'],
  },
  {
    id: 'chapter-cbse-c10-acids-bases-salts',
    courseId: 'course-cbse-c10-chemistry',
    chapterNumber: 2,
    title: 'Acids, Bases and Salts',
    topicIds: ['topic-acids-bases-salts'],
    conceptIds: ['concept-acids-bases', 'concept-ph-indicators', 'concept-neutralisation'],
    simulationIds: ['sim-c10-ch02-a01-introduction-to-acids-and-bases-and-litmus-test'],
  },
];

export const COURSES: CourseRecord[] = [
  {
    id: 'course-cbse-c5-environmental-science',
    title: 'CBSE Class 5 Environmental Studies',
    board: 'cbse',
    classLevel: 5,
    gradeBand: 'class3To5',
    subject: 'environmentalScience',
    description: 'Observation-led environmental science connecting the human body, health, everyday materials, and water.',
    chapterIds: [
      'chapter-cbse-c5-from-tasting-to-digesting',
      'chapter-cbse-c5-water-experiments',
    ],
    conceptIds: [
      'concept-digestive-system',
      'concept-food-journey',
      'concept-nutrient-absorption',
      'concept-digestive-health',
      'concept-solubility',
      'concept-solution',
      'concept-mixture-observation',
    ],
    simulationIds: [
      'sim-c05-ch03-a02-introduction-of-digestive-system',
      'sim-c05-ch07-a03-soluble-and-insoluble-substances',
    ],
    searchKeywords: ['class 5', 'EVS', 'digestive system', 'water experiments'],
  },
  {
    id: 'course-cbse-c6-science',
    title: 'CBSE Class 6 Science',
    board: 'cbse',
    classLevel: 6,
    gradeBand: 'class6To8',
    subject: 'science',
    description: 'Foundational science connecting food, living sources, and daily observation.',
    chapterIds: ['chapter-cbse-c6-food-sources'],
    conceptIds: ['concept-food-sources', 'concept-plant-products', 'concept-animal-products', 'concept-edible-fungi'],
    simulationIds: ['sim-c06-ch01-a01-sources-of-food'],
    searchKeywords: ['class 6', 'food sources', 'ingredients'],
  },
  {
    id: 'course-cbse-c7-biology',
    title: 'CBSE Class 7 Biology',
    board: 'cbse',
    classLevel: 7,
    gradeBand: 'class6To8',
    subject: 'biology',
    description: 'Life-science concepts made visible through plant structure, reproduction, and human respiration.',
    chapterIds: ['chapter-cbse-c7-reproduction-plants', 'chapter-cbse-c7-respiration-organisms'],
    conceptIds: [
      'concept-flower-structure',
      'concept-pollination',
      'concept-fertilisation',
      'concept-seed-germination',
      'concept-respiratory-system',
      'concept-breathing-mechanics',
      'concept-gas-exchange',
    ],
    simulationIds: ['sim-pollination-001', 'sim-c07-ch10-a02-the-breathing-process-in-human'],
    searchKeywords: ['class 7', 'plants', 'pollination', 'respiration', 'breathing', 'lungs'],
  },
  {
    id: 'course-cbse-c8-physics',
    title: 'CBSE Class 8 Physics',
    board: 'cbse',
    classLevel: 8,
    gradeBand: 'class6To8',
    subject: 'physics',
    description: 'Hands-on physical science exploring how force changes motion and shape.',
    chapterIds: ['chapter-cbse-c8-force-and-pressure'],
    conceptIds: ['concept-force-and-motion', 'concept-force-and-shape'],
    simulationIds: ['sim-c08-ch10-a02-the-effects-of-force-on-object-s-motion-and-shape'],
    searchKeywords: ['class 8', 'force', 'pressure', 'motion', 'shape'],
  },
  {
    id: 'course-cbse-c9-science',
    title: 'CBSE Class 9 Science',
    board: 'cbse',
    classLevel: 9,
    gradeBand: 'class9To10',
    subject: 'chemistry',
    description: 'Microscopic models for matter, particles, and energy-driven state change.',
    chapterIds: ['chapter-cbse-c9-matter'],
    conceptIds: ['concept-states-of-matter', 'concept-particle-motion', 'concept-phase-change'],
    simulationIds: ['sim-c09-ch01-a02-states-of-matter'],
    searchKeywords: ['class 9', 'matter', 'particle model'],
  },
  {
    id: 'course-cbse-c10-physics',
    title: 'CBSE Class 10 Physics',
    board: 'cbse',
    classLevel: 10,
    gradeBand: 'class9To10',
    subject: 'physics',
    description: 'Interactive physical science focused on electricity, current, and resistance.',
    chapterIds: ['chapter-cbse-c10-electricity'],
    conceptIds: ['concept-electric-current', 'concept-closed-circuit', 'concept-resistance', 'concept-ohms-law'],
    simulationIds: ['sim-circuit-001'],
    searchKeywords: ['class 10', 'electricity', 'Ohms law'],
  },
  {
    id: 'course-cbse-c10-chemistry',
    title: 'CBSE Class 10 Chemistry',
    board: 'cbse',
    classLevel: 10,
    gradeBand: 'class9To10',
    subject: 'chemistry',
    description: 'Interactive chemistry focused on acids, bases, the pH scale, and neutralisation.',
    chapterIds: ['chapter-cbse-c10-acids-bases-salts'],
    conceptIds: ['concept-acids-bases', 'concept-ph-indicators', 'concept-neutralisation'],
    simulationIds: ['sim-c10-ch02-a01-introduction-to-acids-and-bases-and-litmus-test'],
    searchKeywords: ['class 10', 'acids', 'bases', 'ph', 'neutralisation'],
  },
];
