import type {
  CourseRecord,
  CurriculumChapterRecord,
  LearningConceptRecord,
} from '../../simulation-schema/src/index';

export const LEARNING_CONCEPTS: LearningConceptRecord[] = [
  {
    id: 'concept-flower-structure',
    canonicalName: 'Flower structure',
    aliases: ['parts of a flower', 'stamen and stigma'],
    subject: 'biology',
    description: 'The reproductive structures of a flower and the role each part plays.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-pollination', 'concept-fertilisation'],
    commonMisconceptions: ['All visible flower parts have the same reproductive role.'],
    practicalRelevance: 'Supports observation of flowering crops and plant reproduction.',
    searchKeywords: ['anther', 'stigma', 'ovary', 'petal'],
  },
  {
    id: 'concept-pollination',
    canonicalName: 'Pollination',
    aliases: ['pollen transfer', 'cross-pollination'],
    subject: 'biology',
    description: 'Transfer of pollen from an anther to a compatible stigma.',
    prerequisiteConceptIds: ['concept-flower-structure'],
    relatedConceptIds: ['concept-fertilisation', 'concept-seed-germination'],
    commonMisconceptions: ['Pollination and fertilisation are the same event.'],
    practicalRelevance: 'Explains pollinator value in gardens, orchards, and food production.',
    searchKeywords: ['bee', 'pollinator', 'pollen', 'stigma'],
  },
  {
    id: 'concept-fertilisation',
    canonicalName: 'Fertilisation',
    aliases: ['plant fertilization', 'fusion of gametes'],
    subject: 'biology',
    description: 'Fusion of reproductive cells after successful pollination, leading toward seed formation.',
    prerequisiteConceptIds: ['concept-pollination'],
    relatedConceptIds: ['concept-flower-structure', 'concept-seed-germination'],
    commonMisconceptions: ['A seed forms immediately when pollen touches a flower.'],
    practicalRelevance: 'Connects flower biology to fruit and seed production.',
    searchKeywords: ['ovule', 'ovary', 'seed formation'],
  },
  {
    id: 'concept-seed-germination',
    canonicalName: 'Seed germination',
    aliases: ['germination', 'seed sprouting'],
    subject: 'biology',
    description: 'Growth of a seed into a seedling when water, oxygen, and temperature are suitable.',
    prerequisiteConceptIds: ['concept-fertilisation'],
    relatedConceptIds: ['concept-pollination'],
    commonMisconceptions: ['Seeds germinate without suitable environmental conditions.'],
    practicalRelevance: 'Informs crop sowing, kitchen gardens, and seed care.',
    searchKeywords: ['seedling', 'sprout', 'plant growth'],
  },
  {
    id: 'concept-electric-current',
    canonicalName: 'Electric current',
    aliases: ['current', 'flow of charge'],
    subject: 'physics',
    description: 'The rate of electric charge flow through a conducting path.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-closed-circuit', 'concept-resistance', 'concept-ohms-law'],
    commonMisconceptions: ['Current is consumed by a bulb.'],
    practicalRelevance: 'Supports safe reasoning about appliances, batteries, and circuits.',
    searchKeywords: ['charge', 'ampere', 'electron flow'],
  },
  {
    id: 'concept-closed-circuit',
    canonicalName: 'Closed circuit',
    aliases: ['complete circuit', 'circuit path'],
    subject: 'physics',
    description: 'An unbroken conducting path that allows electric current to flow.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-electric-current', 'concept-resistance'],
    commonMisconceptions: ['A switch creates current rather than completing a path.'],
    practicalRelevance: 'Explains switches, torch circuits, and basic fault finding.',
    searchKeywords: ['switch', 'battery', 'bulb', 'wire'],
  },
  {
    id: 'concept-resistance',
    canonicalName: 'Electrical resistance',
    aliases: ['resistance', 'resistor'],
    subject: 'physics',
    description: 'Opposition to charge flow, measured in ohms.',
    prerequisiteConceptIds: ['concept-electric-current'],
    relatedConceptIds: ['concept-ohms-law', 'concept-closed-circuit'],
    commonMisconceptions: ['Higher resistance makes current move faster.'],
    practicalRelevance: 'Helps select components and understand heating and brightness.',
    searchKeywords: ['ohm', 'resistor value', 'brightness'],
  },
  {
    id: 'concept-ohms-law',
    canonicalName: "Ohm's law",
    aliases: ['V equals IR', 'voltage current resistance'],
    subject: 'physics',
    description: 'The quantitative relationship between voltage, current, and resistance.',
    prerequisiteConceptIds: ['concept-electric-current', 'concept-resistance'],
    relatedConceptIds: ['concept-closed-circuit'],
    commonMisconceptions: ['Voltage and current are interchangeable quantities.'],
    practicalRelevance: 'Enables prediction of current in simple electrical systems.',
    searchKeywords: ['V=IR', 'voltage', 'current calculation'],
  },
  {
    id: 'concept-states-of-matter',
    canonicalName: 'States of matter',
    aliases: ['solid liquid gas', 'phases of matter'],
    subject: 'chemistry',
    description: 'Observable forms of matter produced by different particle arrangements and energies.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-particle-motion', 'concept-phase-change'],
    commonMisconceptions: ['Particles exist only in gases.'],
    practicalRelevance: 'Explains everyday materials, weather, cooking, and storage.',
    searchKeywords: ['solid', 'liquid', 'gas', 'matter'],
  },
  {
    id: 'concept-particle-motion',
    canonicalName: 'Particle motion',
    aliases: ['kinetic particle theory', 'particle movement'],
    subject: 'physics',
    description: 'Microscopic particle speed, spacing, and movement in different states of matter.',
    prerequisiteConceptIds: ['concept-states-of-matter'],
    relatedConceptIds: ['concept-phase-change'],
    commonMisconceptions: ['Particles in solids do not move.'],
    practicalRelevance: 'Builds a mental model for diffusion, heating, and cooling.',
    searchKeywords: ['kinetic energy', 'spacing', 'vibration'],
  },
  {
    id: 'concept-phase-change',
    canonicalName: 'Phase change',
    aliases: ['change of state', 'melting boiling condensation'],
    subject: 'chemistry',
    description: 'A reversible change between states caused by energy transfer.',
    prerequisiteConceptIds: ['concept-states-of-matter', 'concept-particle-motion'],
    relatedConceptIds: [],
    commonMisconceptions: ['Heating creates new particles.'],
    practicalRelevance: 'Explains refrigeration, rainfall, evaporation, and cooking.',
    searchKeywords: ['melting', 'boiling', 'freezing', 'condensation'],
  },
  {
    id: 'concept-food-sources',
    canonicalName: 'Sources of food',
    aliases: ['food origins', 'where food comes from'],
    subject: 'science',
    description: 'Classification of food ingredients by the living source from which they are obtained.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-plant-products', 'concept-animal-products', 'concept-edible-fungi'],
    commonMisconceptions: ['Food source categories are the same as food groups.'],
    practicalRelevance: 'Connects meals and markets to farms, animals, and fungi.',
    searchKeywords: ['ingredients', 'origin', 'meal'],
  },
  {
    id: 'concept-plant-products',
    canonicalName: 'Plant food products',
    aliases: ['plant sources', 'foods from plants'],
    subject: 'biology',
    description: 'Foods obtained from plant parts including seeds, fruits, leaves, roots, and stems.',
    prerequisiteConceptIds: ['concept-food-sources'],
    relatedConceptIds: ['concept-animal-products', 'concept-edible-fungi'],
    commonMisconceptions: ['Only green vegetables are plant products.'],
    practicalRelevance: 'Supports nutrition, farming, and ingredient-label discussions.',
    searchKeywords: ['grain', 'pulse', 'fruit', 'vegetable'],
  },
  {
    id: 'concept-animal-products',
    canonicalName: 'Animal food products',
    aliases: ['animal sources', 'foods from animals'],
    subject: 'biology',
    description: 'Foods obtained from animals, including milk, eggs, honey, meat, and fish.',
    prerequisiteConceptIds: ['concept-food-sources'],
    relatedConceptIds: ['concept-plant-products', 'concept-edible-fungi'],
    commonMisconceptions: ['Milk and honey are plant products.'],
    practicalRelevance: 'Links food choices to dairy, poultry, beekeeping, and fisheries.',
    searchKeywords: ['milk', 'egg', 'honey', 'fish'],
  },
  {
    id: 'concept-edible-fungi',
    canonicalName: 'Edible fungi',
    aliases: ['mushrooms', 'fungal food sources'],
    subject: 'biology',
    description: 'Fungi used as food and their distinction from plants and animals.',
    prerequisiteConceptIds: ['concept-food-sources'],
    relatedConceptIds: ['concept-plant-products', 'concept-animal-products'],
    commonMisconceptions: ['Mushrooms are plants.'],
    practicalRelevance: 'Supports accurate food classification and safe food-source discussion.',
    searchKeywords: ['fungus', 'mushroom', 'decomposer'],
  },
  {
    id: 'concept-solubility',
    canonicalName: 'Solubility',
    aliases: ['soluble and insoluble', 'dissolving in water'],
    subject: 'science',
    description: 'The ability of a substance to dissolve in a solvent under stated conditions.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-solution', 'concept-mixture-observation'],
    commonMisconceptions: ['Dissolving means disappearing.'],
    practicalRelevance: 'Explains cooking, cleaning, water quality, and material separation.',
    searchKeywords: ['dissolve', 'soluble', 'insoluble', 'water'],
  },
  {
    id: 'concept-solution',
    canonicalName: 'Solution',
    aliases: ['solute and solvent', 'uniform mixture'],
    subject: 'chemistry',
    description: 'A mixture in which dissolved particles are distributed through a solvent.',
    prerequisiteConceptIds: ['concept-solubility'],
    relatedConceptIds: ['concept-mixture-observation'],
    commonMisconceptions: ['A clear solution contains no dissolved material.'],
    practicalRelevance: 'Supports preparation and interpretation of everyday mixtures.',
    searchKeywords: ['solute', 'solvent', 'clear mixture'],
  },
  {
    id: 'concept-mixture-observation',
    canonicalName: 'Observing mixtures',
    aliases: ['mixture evidence', 'settling floating separating'],
    subject: 'science',
    description: 'Use of visible evidence to distinguish dissolving, suspension, settling, and layering.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-solubility', 'concept-solution'],
    commonMisconceptions: ['Floating and dissolving describe the same process.'],
    practicalRelevance: 'Supports fair tests, filtration, and water-treatment reasoning.',
    searchKeywords: ['sediment', 'layer', 'cloudy', 'fair test'],
  },
  {
    id: 'concept-digestive-system',
    canonicalName: 'Human digestive system',
    aliases: ['digestive organs', 'human digestion'],
    subject: 'biology',
    description: 'The connected organs that break food down, absorb useful material, and remove solid waste.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-food-journey', 'concept-nutrient-absorption', 'concept-digestive-health'],
    commonMisconceptions: ['Digestion begins only after food reaches the stomach.'],
    practicalRelevance: 'Builds body awareness and explains how food supports growth and activity.',
    searchKeywords: ['mouth', 'esophagus', 'stomach', 'intestine'],
  },
  {
    id: 'concept-food-journey',
    canonicalName: 'Journey of food',
    aliases: ['digestive pathway', 'alimentary canal'],
    subject: 'biology',
    description: 'The ordered movement of food through the mouth, esophagus, stomach, intestines, rectum, and anus.',
    prerequisiteConceptIds: ['concept-digestive-system'],
    relatedConceptIds: ['concept-nutrient-absorption'],
    commonMisconceptions: ['Food passes through the liver, gallbladder, and pancreas.'],
    practicalRelevance: 'Helps students connect eating, swallowing, digestion, and waste removal.',
    searchKeywords: ['food pipe', 'peristalsis', 'chyme', 'waste'],
  },
  {
    id: 'concept-nutrient-absorption',
    canonicalName: 'Nutrient and water absorption',
    aliases: ['villi', 'absorption in intestines'],
    subject: 'biology',
    description: 'Movement of digested nutrients into blood through the small intestine and recovery of water in the large intestine.',
    prerequisiteConceptIds: ['concept-digestive-system', 'concept-food-journey'],
    relatedConceptIds: ['concept-digestive-health'],
    commonMisconceptions: ['The large intestine absorbs most food nutrients.'],
    practicalRelevance: 'Explains how food and water become useful to the whole body.',
    searchKeywords: ['small intestine', 'large intestine', 'blood', 'villi'],
  },
  {
    id: 'concept-digestive-health',
    canonicalName: 'Healthy digestion habits',
    aliases: ['digestive health', 'healthy eating habits'],
    subject: 'environmentalScience',
    description: 'Everyday choices that support digestion, including varied foods, water, chewing, hygiene, and movement.',
    prerequisiteConceptIds: ['concept-digestive-system'],
    relatedConceptIds: ['concept-nutrient-absorption'],
    commonMisconceptions: ['One food alone can keep the digestive system healthy.'],
    practicalRelevance: 'Supports informed choices about meals, hydration, exercise, and hand washing.',
    searchKeywords: ['fruit', 'vegetables', 'water', 'chewing', 'exercise'],
  },
  {
    id: 'concept-money-values',
    canonicalName: 'Money values',
    aliases: ['currency value', 'rupee values'],
    subject: 'mathematics',
    description: 'Understanding that coins and notes represent specific values that can be counted and compared.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-indian-coins-notes', 'concept-simple-shopping'],
    commonMisconceptions: ['All coins or notes have the same value.'],
    practicalRelevance: 'Supports early numeracy in shops, saving, and everyday transactions.',
    searchKeywords: ['rupee', 'value', 'counting money'],
  },
  {
    id: 'concept-indian-coins-notes',
    canonicalName: 'Indian coins and notes',
    aliases: ['Indian currency', 'coins and notes'],
    subject: 'mathematics',
    description: 'Recognition of common Indian currency forms and their written values.',
    prerequisiteConceptIds: ['concept-money-values'],
    relatedConceptIds: ['concept-simple-shopping'],
    commonMisconceptions: ['A larger-looking token always has a larger value.'],
    practicalRelevance: 'Helps children identify money used at home, school events, and shops.',
    searchKeywords: ['coin', 'note', 'currency', 'rupee'],
  },
  {
    id: 'concept-simple-shopping',
    canonicalName: 'Simple shopping with money',
    aliases: ['buying items', 'matching price'],
    subject: 'mathematics',
    description: 'Using money values to choose enough currency for simple priced items.',
    prerequisiteConceptIds: ['concept-money-values', 'concept-indian-coins-notes'],
    relatedConceptIds: [],
    commonMisconceptions: ['Any coin or note can buy any item.'],
    practicalRelevance: 'Connects counting and comparison to safe pretend shopping practice.',
    searchKeywords: ['shop', 'price', 'buy', 'pay'],
  },
  {
    id: 'concept-position-words',
    canonicalName: 'Position words',
    aliases: ['location words', 'spatial words'],
    subject: 'english',
    description: 'Words that describe where one object is in relation to another object.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-spatial-sentences', 'concept-preposition-use'],
    commonMisconceptions: ['In, on, under, and behind can be used interchangeably.'],
    practicalRelevance: 'Supports classroom instructions, reading, speaking, and writing.',
    searchKeywords: ['in', 'on', 'under', 'behind', 'between'],
  },
  {
    id: 'concept-spatial-sentences',
    canonicalName: 'Spatial sentences',
    aliases: ['location sentence', 'where sentence'],
    subject: 'english',
    description: 'Complete sentences that use position words to describe object location clearly.',
    prerequisiteConceptIds: ['concept-position-words'],
    relatedConceptIds: ['concept-preposition-use'],
    commonMisconceptions: ['A position word alone is a complete description.'],
    practicalRelevance: 'Helps children answer where questions in speech and writing.',
    searchKeywords: ['sentence', 'object', 'place', 'where'],
  },
  {
    id: 'concept-preposition-use',
    canonicalName: 'Preposition use',
    aliases: ['using prepositions', 'preposition grammar'],
    subject: 'english',
    description: 'Use of prepositions to show relationships between nouns or pronouns and other words.',
    prerequisiteConceptIds: ['concept-position-words'],
    relatedConceptIds: ['concept-spatial-sentences'],
    commonMisconceptions: ['Prepositions are labels to memorize without object relationships.'],
    practicalRelevance: 'Builds accurate speaking, reading comprehension, and writing.',
    searchKeywords: ['preposition', 'grammar', 'place', 'relationship'],
  },
  {
    id: 'concept-solar-system',
    canonicalName: 'Solar system',
    aliases: ['Sun and planets', 'planetary system'],
    subject: 'science',
    description: 'The Sun, planets, dwarf planets, moons, asteroids, and comets bound together by gravity.',
    prerequisiteConceptIds: [],
    relatedConceptIds: ['concept-planet-order', 'concept-orbits-gravity', 'concept-planet-features'],
    commonMisconceptions: ['The solar system contains only planets.'],
    practicalRelevance: 'Supports astronomy, space missions, satellites, seasons, and night-sky observation.',
    searchKeywords: ['Sun', 'planet', 'moon', 'asteroid', 'comet'],
  },
  {
    id: 'concept-planet-order',
    canonicalName: 'Planet order',
    aliases: ['order of planets', 'Mercury to Neptune'],
    subject: 'science',
    description: 'The sequence of the eight planets from the Sun: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.',
    prerequisiteConceptIds: ['concept-solar-system'],
    relatedConceptIds: ['concept-planet-features'],
    commonMisconceptions: ['Pluto is one of the eight main planets.'],
    practicalRelevance: 'Creates a foundation for comparing distance, temperature, and orbital periods.',
    searchKeywords: ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
  },
  {
    id: 'concept-orbits-gravity',
    canonicalName: 'Orbits and gravity',
    aliases: ['planet orbits', 'gravity in space'],
    subject: 'physics',
    description: 'Gravity keeps planets and other bodies moving along orbital paths around larger bodies.',
    prerequisiteConceptIds: ['concept-solar-system'],
    relatedConceptIds: ['concept-planet-order'],
    commonMisconceptions: ['Planets move because there is no gravity in space.'],
    practicalRelevance: 'Explains satellites, moon motion, planetary years, and spaceflight paths.',
    searchKeywords: ['orbit', 'gravity', 'path', 'satellite'],
  },
  {
    id: 'concept-planet-features',
    canonicalName: 'Planet features',
    aliases: ['planet properties', 'rocky and gas planets'],
    subject: 'science',
    description: 'Observable and modelled differences between planets, including size, surface, atmosphere, rings, and moons.',
    prerequisiteConceptIds: ['concept-solar-system'],
    relatedConceptIds: ['concept-planet-order', 'concept-orbits-gravity'],
    commonMisconceptions: ['All planets have solid surfaces like Earth.'],
    practicalRelevance: 'Supports comparison, classification, and evidence-based space learning.',
    searchKeywords: ['rocky planet', 'gas giant', 'rings', 'atmosphere'],
  },
];

export const CURRICULUM_CHAPTERS: CurriculumChapterRecord[] = [
  {
    id: 'chapter-cbse-c1-math-money',
    courseId: 'course-cbse-c1-mathematics',
    chapterNumber: 1,
    title: 'Introduction to Money',
    topicIds: ['topic-money-values'],
    conceptIds: ['concept-money-values', 'concept-indian-coins-notes', 'concept-simple-shopping'],
    simulationIds: ['sim-c1-math-ch01-introduction-to-money'],
  },
  {
    id: 'chapter-cbse-c2-english-prepositions',
    courseId: 'course-cbse-c2-english',
    chapterNumber: 1,
    title: 'Prepositions',
    topicIds: ['topic-position-words'],
    conceptIds: ['concept-position-words', 'concept-spatial-sentences', 'concept-preposition-use'],
    simulationIds: ['sim-c2-english-ch01-prepositions'],
  },
  {
    id: 'chapter-cbse-c5-from-tasting-to-digesting',
    courseId: 'course-cbse-c5-environmental-science',
    chapterNumber: 3,
    title: 'From Tasting to Digesting',
    topicIds: ['topic-human-digestive-system'],
    conceptIds: [
      'concept-digestive-system',
      'concept-food-journey',
      'concept-nutrient-absorption',
      'concept-digestive-health',
    ],
    simulationIds: ['sim-c05-ch03-a02-introduction-of-digestive-system'],
  },
  {
    id: 'chapter-cbse-c5-water-experiments',
    courseId: 'course-cbse-c5-environmental-science',
    chapterNumber: 7,
    title: 'Experiments with Water',
    topicIds: ['topic-soluble-insoluble'],
    conceptIds: ['concept-solubility', 'concept-solution', 'concept-mixture-observation'],
    simulationIds: ['sim-c05-ch07-a03-soluble-and-insoluble-substances'],
  },
  {
    id: 'chapter-cbse-c6-food-sources',
    courseId: 'course-cbse-c6-science',
    chapterNumber: 1,
    title: 'Food: Where Does It Come From?',
    topicIds: ['topic-food-origins'],
    conceptIds: ['concept-food-sources', 'concept-plant-products', 'concept-animal-products', 'concept-edible-fungi'],
    simulationIds: ['sim-c06-ch01-a01-sources-of-food'],
  },
  {
    id: 'chapter-cbse-c7-reproduction-plants',
    courseId: 'course-cbse-c7-biology',
    chapterNumber: 12,
    title: 'Reproduction in Plants',
    topicIds: ['topic-pollination-growth-cycle'],
    conceptIds: ['concept-flower-structure', 'concept-pollination', 'concept-fertilisation', 'concept-seed-germination'],
    simulationIds: ['sim-pollination-001'],
  },
  {
    id: 'chapter-cbse-c8-solar-system',
    courseId: 'course-cbse-c8-science',
    chapterNumber: 17,
    title: 'Stars and the Solar System',
    topicIds: ['topic-solar-system'],
    conceptIds: ['concept-solar-system', 'concept-planet-order', 'concept-orbits-gravity', 'concept-planet-features'],
    simulationIds: ['sim-c8-10-science-solar-system'],
  },
  {
    id: 'chapter-cbse-c9-matter',
    courseId: 'course-cbse-c9-science',
    chapterNumber: 1,
    title: 'Matter in Our Surroundings',
    topicIds: ['topic-particle-model'],
    conceptIds: ['concept-states-of-matter', 'concept-particle-motion', 'concept-phase-change'],
    simulationIds: ['sim-c09-ch01-a02-states-of-matter'],
  },
  {
    id: 'chapter-cbse-c10-electricity',
    courseId: 'course-cbse-c10-physics',
    chapterNumber: 12,
    title: 'Electricity',
    topicIds: ['topic-current-resistance'],
    conceptIds: ['concept-electric-current', 'concept-closed-circuit', 'concept-resistance', 'concept-ohms-law'],
    simulationIds: ['sim-circuit-001'],
  },
];

export const COURSES: CourseRecord[] = [
  {
    id: 'course-cbse-c1-mathematics',
    title: 'CBSE Class 1 Mathematics',
    board: 'cbse',
    classLevel: 1,
    gradeBand: 'class1To2',
    subject: 'mathematics',
    description: 'Early mathematics built around counting, comparison, money, and everyday number sense.',
    chapterIds: ['chapter-cbse-c1-math-money'],
    conceptIds: ['concept-money-values', 'concept-indian-coins-notes', 'concept-simple-shopping'],
    simulationIds: ['sim-c1-math-ch01-introduction-to-money'],
    searchKeywords: ['class 1', 'money', 'coins', 'notes', 'rupees'],
  },
  {
    id: 'course-cbse-c2-english',
    title: 'CBSE Class 2 English',
    board: 'cbse',
    classLevel: 2,
    gradeBand: 'class1To2',
    subject: 'english',
    description: 'Foundational English language practice through listening, speaking, grammar, and everyday sentences.',
    chapterIds: ['chapter-cbse-c2-english-prepositions'],
    conceptIds: ['concept-position-words', 'concept-spatial-sentences', 'concept-preposition-use'],
    simulationIds: ['sim-c2-english-ch01-prepositions'],
    searchKeywords: ['class 2', 'english', 'prepositions', 'position words'],
  },
  {
    id: 'course-cbse-c5-environmental-science',
    title: 'CBSE Class 5 Environmental Studies',
    board: 'cbse',
    classLevel: 5,
    gradeBand: 'class3To5',
    subject: 'environmentalScience',
    description: 'Observation-led environmental science connecting the human body, health, everyday materials, and water.',
    chapterIds: [
      'chapter-cbse-c5-from-tasting-to-digesting',
      'chapter-cbse-c5-water-experiments',
    ],
    conceptIds: [
      'concept-digestive-system',
      'concept-food-journey',
      'concept-nutrient-absorption',
      'concept-digestive-health',
      'concept-solubility',
      'concept-solution',
      'concept-mixture-observation',
    ],
    simulationIds: [
      'sim-c05-ch03-a02-introduction-of-digestive-system',
      'sim-c05-ch07-a03-soluble-and-insoluble-substances',
    ],
    searchKeywords: ['class 5', 'EVS', 'digestive system', 'water experiments'],
  },
  {
    id: 'course-cbse-c6-science',
    title: 'CBSE Class 6 Science',
    board: 'cbse',
    classLevel: 6,
    gradeBand: 'class6To8',
    subject: 'science',
    description: 'Foundational science connecting food, living sources, and daily observation.',
    chapterIds: ['chapter-cbse-c6-food-sources'],
    conceptIds: ['concept-food-sources', 'concept-plant-products', 'concept-animal-products', 'concept-edible-fungi'],
    simulationIds: ['sim-c06-ch01-a01-sources-of-food'],
    searchKeywords: ['class 6', 'food sources', 'ingredients'],
  },
  {
    id: 'course-cbse-c7-biology',
    title: 'CBSE Class 7 Biology',
    board: 'cbse',
    classLevel: 7,
    gradeBand: 'class6To8',
    subject: 'biology',
    description: 'Life-science concepts made visible through plant structure and reproduction.',
    chapterIds: ['chapter-cbse-c7-reproduction-plants'],
    conceptIds: ['concept-flower-structure', 'concept-pollination', 'concept-fertilisation', 'concept-seed-germination'],
    simulationIds: ['sim-pollination-001'],
    searchKeywords: ['class 7', 'plants', 'pollination'],
  },
  {
    id: 'course-cbse-c8-science',
    title: 'CBSE Class 8 Science',
    board: 'cbse',
    classLevel: 8,
    gradeBand: 'class6To8',
    subject: 'science',
    description: 'Middle-school science connecting space, matter, force, living systems, and technology through observable models.',
    chapterIds: ['chapter-cbse-c8-solar-system'],
    conceptIds: ['concept-solar-system', 'concept-planet-order', 'concept-orbits-gravity', 'concept-planet-features'],
    simulationIds: ['sim-c8-10-science-solar-system'],
    searchKeywords: ['class 8', 'solar system', 'planets', 'space'],
  },
  {
    id: 'course-cbse-c9-science',
    title: 'CBSE Class 9 Science',
    board: 'cbse',
    classLevel: 9,
    gradeBand: 'class9To10',
    subject: 'chemistry',
    description: 'Microscopic models for matter, particles, and energy-driven state change.',
    chapterIds: ['chapter-cbse-c9-matter'],
    conceptIds: ['concept-states-of-matter', 'concept-particle-motion', 'concept-phase-change'],
    simulationIds: ['sim-c09-ch01-a02-states-of-matter'],
    searchKeywords: ['class 9', 'matter', 'particle model'],
  },
  {
    id: 'course-cbse-c10-physics',
    title: 'CBSE Class 10 Physics',
    board: 'cbse',
    classLevel: 10,
    gradeBand: 'class9To10',
    subject: 'physics',
    description: 'Interactive physical science focused on electricity, current, and resistance.',
    chapterIds: ['chapter-cbse-c10-electricity'],
    conceptIds: ['concept-electric-current', 'concept-closed-circuit', 'concept-resistance', 'concept-ohms-law'],
    simulationIds: ['sim-circuit-001'],
    searchKeywords: ['class 10', 'electricity', 'Ohms law'],
  },
];
